CONTRIBUTING.md

It seems header links must not have upper-case letters.

Fix anchors in the contribution guide.

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Travis links should be changed to https://www.travis-ci.org.
---

Change travis-ci.com to travis-ci.org

---

exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTx.java
exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/TransferTx.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/Counter.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/CreateCounterTx.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/IncrementCounterTx.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/ValidThrowingTx.java

Replace Guava Objects with java.util.Objects as after Java 7 the former should be considered deprecated ( https://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/Objects.html#hashCode(java.lang.Object...) ).
---
See: https://jira.bf.local/browse/ECR-1725

ECR-1725 Replace Guava Objects with java.util.Objects

---

exonum-java-binding-bom/pom.xml
exonum-java-binding-cryptocurrency-demo/pom.xml
exonum-java-binding-qa-service/pom.xml

The core requires the AOP-enabled flavour of Guice, therefore,
all depending modules must use the same.

Use the same flavour of Guice across the project:

---

exonum-java-binding-core/pom.xml
exonum-java-binding-service-archetype/src/main/resources/archetype-resources/pom.xml

As error-prone does not support Java 10 yet, remove obsolete
configurations:
- Remove an obsolete profile from the pom.xml of the core module.
- Replace the compiler configuration in the generated archetype
with the standard one.
See also:
35012e242ba6797275917e0a5748ea51d86cc0f4 (the 1st incomplete patch)
---
See also: https://jira.bf.local/browse/ECR-1746

Use the standard javac instead of error-prone 2:

---

exonum-java-binding-core/rust/src/storage/list_index.rs

A no longer relevant "todo" was removed.
---
See: https://jira.bf.local/browse/ECR-1506

Remove a no longer relevant todo [ECR-1506].

---

exonum-java-binding-core/checkstyle-suppressions.xml
exonum-java-binding-core/src/main/java/com/exonum/binding/messages/BinaryMessage.java
exonum-java-binding-core/src/main/java/com/exonum/binding/messages/Message.java
exonum-java-binding-core/src/main/java/com/exonum/binding/messages/MessageReader.java
exonum-java-binding-core/src/main/java/com/exonum/binding/messages/Message_Builder2.java
exonum-java-binding-core/src/main/java/com/exonum/binding/service/NodeProxy.java
exonum-java-binding-core/src/test/java/com/exonum/binding/messages/BinaryMessageBuilderTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/messages/BinaryMessageTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/messages/MessageReaderTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/messages/MessageTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/messages/Message_Builder2Test.java
exonum-java-binding-core/src/test/java/com/exonum/binding/messages/TemplateMessage.java
exonum-java-binding-core/src/test/java/com/exonum/binding/service/ServiceBootstrapIntegrationTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/service/adapters/UserServiceAdapterTest.java
exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/CryptocurrencyTransactionTemplate.java
exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/JsonBinaryMessageConverter.java
exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTxTest.java
exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/JsonBinaryMessageConverterTest.java
exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxTest.java
exonum-java-binding-fakes/src/test/java/com/exonum/binding/fakes/services/service/PutValueTransactionTest.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/QaTransactionTemplate.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/UnknownTx.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/CreateCounterTxIntegrationTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/QaTransactionConverterTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/Transactions.java
pom.xml

Added `getMessageNoSignature` to get the part of the message
without the signature, and made `getSignature` return a byte array,
so that it’s easier to use with our present cryptographic APIs
that accept byte arrays.
---
See: https://jira.bf.local/browse/ECR-1755

Add operations to get message and its signature from the packet [ECR-1755]

---

exonum-java-binding-core/src/main/java/com/exonum/binding/service/adapters/UserServiceAdapter.java
exonum-java-binding-core/src/test/java/com/exonum/binding/service/adapters/UserServiceAdapterTest.java

Some application expect paths of REST APIs to start with '/api' prefix
(e.g., proxies).

Prepend /api before the path to the API of a service.

---

exonum-java-binding-core/rust/src/storage/proof_map_index.rs

Native getProof method.
Does not support proof of absence. 
Does not includes tests (yet)
Formatting and code readability is awful (yet)
---
See: https://jira.bf.local/browse/XYZ

Add native support for flat proofs [ECR-1350]

---

.travis.yml

`cargo fmt -- --write-mode=diff` does not fail tests now if bad formatting is detected.
`cargo fmt -- --write-mode=check` should be used instead.

Fix rustfmt on travis.

---

exonum-java-binding-core/rust/ejb-app/start_qa_node.sh

Debug flag is no longer used, we need to use ejb-jvm-args instead
---
See: https://jira.bf.local/browse/XYZ

Fix start_qa_node script after adding JVM arguments.

---

.travis.yml
CONTRIBUTING.md
ROADMAP.md
exonum-java-binding-core/pom.xml
exonum-java-binding-core/rust/ejb-app/TUTORIAL.md
exonum-java-binding-core/rust/ejb-app/start_cryptocurrency_node.sh
exonum-java-binding-core/rust/ejb-app/start_qa_node.sh
run_all_tests.sh
run_ejb_app_tests.sh
run_native_integration_tests.sh

We're going to use Rust 1.26.2 until next release because of bug in Cargo.
**However, we're using latest stable Rust for rustfmt.**
---
See: https://jira.bf.local/browse/ECR-1839

Rollback Rust compiler version [ECR-1853]

---

exonum-java-binding-bom/pom.xml
pom.xml

The POMs of child modules that are not published
always include the maven-deploy-plugin
(to alter the configuration, inherited from the parent only
in "deploy-sign-artifacts" profile), but do not specify the version,
which causes warnings during normal builds.
Also, remove redundant properties that are inherited from the parent POM
and may be re-used in the POM of this module.
---

Fix the build warning

---

CHANGELOG.md

Update changelog after v0.2 - move changes from Unreleased to v0.2.
---

Update changelog after v0.2

---

.travis.yml
exonum-java-binding-core/pom.xml
exonum-java-binding-cryptocurrency-demo/pom.xml
exonum-java-binding-service-archetype/pom.xml
exonum-java-binding-service-archetype/src/main/resources/archetype-resources/pom.xml
pom.xml

- Bump maven-resources-plugin from 3.0.2 to 3.1.0:
- [Release notes](https://github.com/apache/maven-resources-plugin/releases)
- [Commits](https://github.com/apache/maven-resources-plugin/compare/maven-resources-plugin-3.0.2...maven-resources-plugin-3.1.0)
- Bump vertx.version from 3.5.2 to 3.5.3
- Updates `vertx-web-client` from 3.5.2 to 3.5.3
- Updates `vertx-unit` from 3.5.2 to 3.5.3
- Updates `vertx-web` from 3.5.2 to 3.5.3
- Updates `vertx-codegen` from 3.5.2 to 3.5.3
- Bump mockito-core from 2.18.3 to 2.19.1:
- [Release notes](https://github.com/mockito/mockito/releases)
- [Commits](https://github.com/mockito/mockito/compare/v2.18.3...v2.19.1)
- Bump spotbugs-maven-plugin from 3.1.5 to 3.1.6:
- [Release notes](https://github.com/spotbugs/spotbugs-maven-plugin/releases)
- …

Bump versions of dependencies:

---

CHANGELOG.md
exonum-java-binding-core/src/main/java/com/exonum/binding/crypto/Ed25519CryptoFunction.java
exonum-java-binding-core/src/test/java/com/exonum/binding/util/LoggingInterceptorTest.java
exonum-java-proofs/src/main/java/com/exonum/binding/hash/AbstractHasher.java
exonum-java-proofs/src/main/java/com/exonum/binding/hash/Hashing.java
exonum-java-proofs/src/test/java/com/exonum/binding/hash/HashingTest.java
exonum-java-proofs/src/test/java/com/exonum/binding/storage/proofs/list/ProofListElementTest.java
exonum-java-proofs/src/test/java/com/exonum/binding/storage/proofs/map/MapProofValidatorMatchers.java
exonum-java-testing/src/main/java/com/exonum/binding/test/Bytes.java
exonum-java-testing/src/test/java/com/exonum/binding/test/BytesTest.java

- Add missing 'final' modifier.
- Suppress a warning.
- Remove Hashing#toHexString: this method does not belong in `Hashing`, and used in a single place only.

Smallish improvements

---

exonum-java-binding-core/rust/cargo.sh
exonum-java-binding-core/rust/ejb-app/TUTORIAL.md
exonum-java-binding-core/rust/ejb-app/start_cryptocurrency_node.sh
exonum-java-binding-core/rust/ejb-app/start_qa_node.sh
run_ejb_app_tests.sh
run_native_integration_tests.sh

The script depends on the line containing "Java home" string in the output of the 'mvn --version' command, which doesn't have this line. This is fair for Maven 3.5.4 with JDK 1.8.0 and JDK 10.0.2.
Besides that, I prefer rather check whether $JAVA_HOME is defined in the user's environment, than extract it from the third-party command (which could change it's output somewhere in the future).
Anyway, this PR fixes build of the exonum-java-binding-core.
Thanks.

Set JAVA_HOME according to the information provided by java itself

---

pom.xml

Skip generating Javadocs in the dev environment and on the CI server.
---
See: https://jira.bf.local/browse/ECR-1833

Skip generating Javadocs in the dev environment [ECR-1833]:

---

CHANGELOG.md
exonum-java-binding-core/checkstyle-suppressions.xml
exonum-java-binding-core/src/main/java/com/exonum/binding/messages/Transaction.java
exonum-java-binding-core/src/main/java/com/exonum/binding/messages/TransactionExecutionException.java
exonum-java-binding-core/src/main/java/com/exonum/binding/service/adapters/UserTransactionAdapter.java
exonum-java-binding-core/src/test/java/com/exonum/binding/messages/TransactionExecutionExceptionTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/service/adapters/UserTransactionAdapterTest.java
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/ThrowingTransactions.java
exonum-java-binding-fakes/src/test/java/com/exonum/binding/fakes/mocks/ThrowingTransactionsTest.java

Add `TransactionExecutionException`. Such exception is thrown to indicate that the transaction cannot be executed and any changes must be rolled back. Its error code is included in the blockchain and can be requested by a client.
This exception corresponds to ExecutionError in the framework native API.
Also, add a method to create a transaction mock throwing `TransactionExecutionException` to be able to test the new behaviour in the native proxy code.
---
See: https://jira.bf.local/browse/ECR-1958

Add TransactionExecutionException [ECR-1958]:

---

.gitignore
exonum-java-binding-core/rust/Cargo.lock

Cargo.lock is now included in the repository in order to avoid `failure` bug while using exonum 0.8.1.
---

Include Cargo.lock

---

CHANGELOG.md
exonum-java-binding-core/src/main/java/com/exonum/binding/messages/Message.java
exonum-java-binding-core/src/test/java/com/exonum/binding/messages/Message_Builder2Test.java
exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/JsonBinaryMessageConverter.java
exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTxTest.java
exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxTest.java
exonum-java-binding-fakes/src/test/java/com/exonum/binding/fakes/services/service/PutValueTransactionTest.java
exonum-java-binding-qa-service/pom.xml
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/ApiController.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/QaSchema.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/QaService.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/CreateCounterTx.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/IncrementCounterTx.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/QaTransaction.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/QaTransactionConverter.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/ValidErrorTx.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/ValidThrowingTx.java
exonum-java-binding-qa-service/src/main/proto/transactions.proto
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/ApiControllerIntegrationTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/CreateCounterTxIntegrationTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/IncrementCounterTxIntegrationTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/QaTransactionConverterTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/ValidErrorTxIntegrationTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/ValidErrorTxTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/ValidThrowingTxTest.java

Add ValidError transaction — a QA service transaction 
that always throws a new TransactionExecutionException 
in its execute after clearing all service collections. It is needed
to test conversion of this exception to the native ExecutionError.
Also, migrate all existing transactions to protobuf
to increase maintainability.
Add Message.Builder#setBody(byte[]) accepting byte arrays to avoid
ByteBuffer.wrap in case the client code needs to pass message body
as a byte array. It turns out most internal usages indeed have
a byte array.
---
See: https://jira.bf.local/browse/ECR-1958
https://jira.bf.local/browse/ECR-1995
https://jira.bf.local/browse/ECR-2011

Add ValidError transaction [ECR-1995]

---

.travis.yml
run_maven_tests.sh
run_native_integration_tests.sh
tests_profile

The logic enabling tests has been moved to Maven build definitions,
therefore, there is no need to set the global user property
that will disable *all* tests (see 5e2055d).
Also, when compiling artefacts in run_native_integration_tests.sh,
there is no need to pass -DskipTests.
---

Fix scripts running tests [ECR-1993]:

---

.travis.yml
exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
exonum-java-binding-core/rust/integration_tests/src/test_service.rs
exonum-java-binding-core/rust/integration_tests/tests/local_frame_capacity.rs
exonum-java-binding-core/rust/integration_tests/tests/local_frame_memory_leak_executor.rs
exonum-java-binding-core/rust/integration_tests/tests/local_frame_memory_leak_jvm.rs
exonum-java-binding-core/rust/src/proxy/executors.rs
exonum-java-binding-core/rust/src/proxy/transaction.rs
exonum-java-binding-core/rust/src/runtime/java_service_runtime.rs
exonum-java-binding-core/rust/src/storage/map_index.rs
exonum-java-binding-core/rust/src/storage/proof_map_index.rs
exonum-java-binding-core/rust/src/storage/value_set_index.rs
exonum-java-binding-core/rust/src/utils/jni.rs

Rustfmt pass, also travis.yml script updated as rustfmt parameters have changed
---

Apply rustfmt from Rust 1.28

---

exonum-java-binding-cryptocurrency-demo/pom.xml
pom.xml

- Update JUnit to 5.3.0-M1.
- Also fix the cryptocurrency build definition so that it does not include duplicated dependencies.

Update JUnit to 5.3.0-M1

---

exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java

Fixes (hopefully) a flaky QaServiceImplIntegrationTest,
which used to run the tests depending on the native library
on Linux, which is not currently supported (see ECR-942).
The problem occurred on both 8 and 10:
```
[INFO] Running com.exonum.binding.qaservice.QaServiceImplIntegrationTest12:07:49.701 [main] ERROR com.exonum.binding.qaservice.QaService - state hashes: [0000000000000000000000000000000000000000000000000000000000000000]*** 
Error in `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java': double free or corruption (out): 0x00007f261daec640 *** 
```
---
See: https://jira.bf.local/browse/ECR-2170

Add missing RequiresNativeLibrary [ECR-2170]:

---

exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/transactions/ValidErrorTxIntegrationTest.java

Since execute uses a fork to access the storage,
passing a mock of a fork does not work.

Fix broken integration tests

---

exonum-java-proofs/src/main/java/com/exonum/binding/storage/proofs/map/DbKey.java
exonum-java-proofs/src/test/java/com/exonum/binding/storage/proofs/map/DbKeyCommonPrefixParameterizedTest.java
exonum-java-proofs/src/test/java/com/exonum/binding/storage/proofs/map/DbKeyTestUtils.java

- Deduplicate code in DbKeyTestUtils
- Simplify the code: 
If keys are equal or one is a prefix of another with trailing zeros
in their prefixes we can just use `this` key slice.
- Add more test cases and remove obsolete:
- Test that commonPrefix is commutative and reflexive.
- Remove old tests of commutativity and reflexivity.
- Simplify some tests.
---

ECR-1164 improvements

---

.travis/run_travis_job.sh

Build gets stuck sometimes because of this check.
---
See: https://jira.bf.local/browse/ECR-2252

Disable check for updates of Maven dependencies [ECR-2252]

---

exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/ApiControllerTest.java
exonum-java-binding-cryptocurrency-demo/src/test/resources/log4j2-test.xml
exonum-java-binding-qa-service/src/test/resources/log4j2-test.xml
exonum-java-proofs/src/test/resources/log4j2-test.xml

Redundant Slf4J tests warnings removed from console output.
---
See: https://jira.bf.local/browse/ECR-1602

[ECR-1602] Redundant tests warnings removed from console output.

---

exonum-java-proofs/src/main/java/com/exonum/binding/storage/proofs/map/flat/UncheckedFlatMapProof.java
exonum-java-proofs/src/test/java/com/exonum/binding/storage/proofs/map/flat/UncheckedFlatMapProofTest.java

- Reorder methods to match the call order
- Check order _before_ checking for included prefixes: otherwise we cannot guarantee the ordering in `prefixesIncluded`.
- Make `proofList` a local, document the preconditions clearer. 
- Fix hash calculation for singleton maps.
---
See: 
- https://jira.bf.local/browse/ECR-1164
- #250

Ecr 1164 improvements

---

CHANGELOG.md

Changelog update after #250 and #457.

Update changelog after #250 and #457

---

CHANGELOG.md

Changelog updated. Includes changes description after modules refactoring: #459 #467 and #469 PRs

Changelog update for #459, #467 and #469 PRs

---

README.md

- We finally migrated to travis.com
- The Maven badge showed 0.1 for no reason.
---

Update travis link and maven badge

---

exonum-java-binding-core/src/test/java/com/exonum/binding/proxy/CleanerTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/testutils/LoggingTestUtils.java
exonum-java-binding-core/src/test/java/com/exonum/binding/util/LoggingInterceptorTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java

If it is not cleared, then the previous tests might affect
the outcome of the test using the appender to assert on logged
messages.
Discovered on Sergey’s machine — strange this unit test worked on all the other installations.

Clear the list log appender before each test.

---

.travis.yml
.travis/run_travis_job.sh
CONTRIBUTING.md
exonum-java-binding-core/pom.xml
exonum-java-binding-core/rust/Cargo.lock
exonum-java-binding-core/rust/Cargo.toml
exonum-java-binding-core/rust/ejb-app/Cargo.toml
exonum-java-binding-core/rust/ejb-app/start_cryptocurrency_node.sh
exonum-java-binding-core/rust/ejb-app/start_qa_node.sh
exonum-java-binding-core/rust/integration_tests/Cargo.toml
exonum-java-binding-core/rust/integration_tests/src/executor.rs
exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
exonum-java-binding-core/rust/integration_tests/src/test_service.rs
exonum-java-binding-core/rust/integration_tests/tests/local_frame_capacity.rs
exonum-java-binding-core/rust/integration_tests/tests/local_frame_memory_leak_executor.rs
exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs
exonum-java-binding-core/rust/src/lib.rs
exonum-java-binding-core/rust/src/proxy/node.rs
exonum-java-binding-core/rust/src/proxy/service.rs
exonum-java-binding-core/rust/src/proxy/transaction.rs
exonum-java-binding-core/rust/src/runtime/java_service_runtime.rs
exonum-java-binding-core/rust/src/storage/map_index.rs
exonum-java-binding-core/rust/src/storage/proof_map_index.rs
exonum-java-binding-core/rust/src/storage/value_set_index.rs
package_app.sh
tests_profile

Added support for Exonum 0.9.2 
Big thanks to @aleksuss 
Runs without issues locally.
Rust has been updated to version 1.27.2, which breaks EJB App building in master.
---
See: https://jira.bf.local/browse/ECR-1896

Migrate to Exonum 0.9.2 [ECR-1896]

---

.travis.yml

As Travis builds both branches and PRs by default, it will create two
builds for a single PR that uses a branch pushed to a repo.
To avoid that (and longer queues for other builds), specify
protected-only to be built.
One can still create WIP PRs to get them built on Travis if they need.
See https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
---
See: https://jira.bf.local/browse/ECR-2386

Build only specific pushed branches [ECR-2386]:

---

exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/flat/CheckedFlatMapProof.java
exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/flat/MapEntry.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/CheckedMapProofMatcher.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/CheckedMapProofMatcherTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ProofMapContainsMatcher.java

It did not work correctly in case of invalid proofs,
throwing IllegalStateException.
Also, improve the descriptions of messages in matchers.

Fix CheckedMapProofMatcher in case of invalid proofs [ECR-1950]

---

CHANGELOG.md
exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/flat/CheckedFlatMapProof.java
exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/flat/MapEntry.java
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/ProofMapIndexProxy.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/CheckedMapProofMatcher.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/CheckedMapProofMatcherTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ProofMapContainsMatcher.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ProofMapIndexProxyIntegrationTest.java

Old proof is replaced with flat map proof in ProofMapIndexProxy.
ITs are modified to check scenarios with single key (either found or absent).
Tests with multiple keys will be covered in separate PR (as well as removing redundant classes).
---
See: https://jira.bf.local/browse/ECR-1950

ECR-1950 Replace tree proof with flat proof in ProofMapIndexProxy

---

.travis/run_travis_job.sh

Updated command that checks whether cargo-audit is installed.
---
See: https://jira.bf.local/browse/ECR-2133

Command to check whether audit crate is installed (see ECR-2133)

---

exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
exonum-java-binding-core/rust/integration_tests/tests/transaction_proxy.rs
exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs
exonum-java-binding-core/rust/src/proxy/transaction.rs
exonum-java-binding-core/rust/src/utils/errors.rs
exonum-java-binding-core/rust/src/utils/mod.rs
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/NativeFacade.java
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/TestTxExecException.java
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/ThrowingTransactions.java
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/test/TestTxExecException.java
exonum-java-binding-fakes/src/test/java/com/exonum/binding/fakes/mocks/ThrowingTransactionsTest.java

The result of execution of a transaction is treated in a little different way now: any JNI error or Java throwable that _is not_ an instance or subclass of the `TransactionExecutionException` considered an unexpected exception and causes panic. `TransactionExecutionException` and its descendants are converted into `Error`s with their descriptions. Former behavior: JNI errors and anything other than `lang.java.Exception` and its descendants considered unexpected exception --> panic.
---
See: https://jira.bf.local/browse/ECR-1956

Update TransactionProxy#execute to use transaction status from Java [ECR-1956]

---

exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/HistoryEntitySerializer.java
exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTx.java
exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/JsonBinaryMessageConverter.java
exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/TransferTx.java
exonum-java-binding-cryptocurrency-demo/src/main/proto/transactions.proto
exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTxTest.java
exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/JsonBinaryMessageConverterTest.java
exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxTest.java

While working on ECR-1523 I noticed that we have inconsistent naming for TxMessageProtos and TxMessagesProtos in QA service and crypto demo service. After this fix we'll need to exclude less patterns of generated classes in Jacoco config.

Rename TxMessagesProtos in crypto demo

---

.travis.yml

Right now openjdk8 OSX builds use JDK 10. In order to use the correct JDK version, we need to use corresponding `osx_image`.
https://docs.travis-ci.com/user/reference/osx/#jdk-and-os-x

Use osx_image instead of jdk for OSX builds

---

.travis.yml

This allows to reduce the time it takes to update and upload
the cache.
---

Remove the project artifacts before uploading the cache

---

exonum-java-binding-common/src/test/java/com/exonum/binding/common/hash/MessageDigestHashFunctionTest.java
exonum-java-binding-common/src/test/java/com/exonum/binding/common/message/ByteBufferAllocator.java
exonum-java-binding-common/src/test/java/com/exonum/binding/common/proofs/map/MapProofValidatorTest.java
exonum-java-binding-common/src/test/java/com/exonum/binding/test/EqualsTester.java

- Clarify conditions using matchers to ease reading and error-reporting
- Reduce visibility of test classes to package-private 
---
See: https://jira.bf.local/browse/ECR-2112

Ecr 2112 improvements

---

exonum-java-binding-common/src/test/java/com/exonum/binding/common/serialization/StandardSerializersRoundtripTest.java

… and some all-zero input of various sizes.
---

Test hash code serializer using the likely 32-byte input

---

CHANGELOG.md
exonum-java-binding-common/src/main/java/com/exonum/binding/common/serialization/Serializer.java
exonum-java-binding-core/pom.xml
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/EntryIndexProxy.java
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/KeySetIndexProxy.java
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/ListIndexProxy.java
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/MapIndexProxy.java
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/ProofListIndexProxy.java
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/ProofMapIndexProxy.java
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/ValueSetIndexProxy.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/IndexConstructors.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ListIndexParameterizedIntegrationTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/MapIndexProxyIntegrationTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/PrefixNameParameterizedIntegrationTest.java
exonum-java-binding-core/src/test/proto/TestMessages.proto

Update indexes to accept proto messages
Make them automatically create reflective serializers of
protobuf messages in their static factory methods.
*Note 1:* ProofMapIndexProxy does not get such a method —
it has a certain restriction on keys, which is unlikely
to hold for an arbitrary Protocol Buffers message.
*Note 2:* dependency on protobuf cannot be optional
because the compiler has to load the classes appearing
in parameter lists to determine which of the overloaded
methods to call. It can be optional if we _require_
the clients to add it in "provided" scope.
Also, avoid overloads by method reference. Because of some
compiler bug in JDK 8, a call like
IndexConstructors.from(ListIndexProxy::newInstance)
cannot be resolved as ambiguous. The same code compiles fine on 11.
\+ Improve the …

Update collections to accept proto messages [ECR-2340]

---

exonum-java-binding-common/pom.xml
exonum-java-binding-core/pom.xml
exonum-java-binding-cryptocurrency-demo/pom.xml
exonum-java-binding-fakes/pom.xml
exonum-java-binding-qa-service/pom.xml
pom.xml

Added jacoco default parameters to use with no profiles set.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project exonum-java-binding-common: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/exonum-java-binding/exonum-java-binding-common/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /root/exonum-java-binding/exonum-java-binding-common && /usr/lib/jvm/java-8-oracle/jre/bin/java '${argLine}' -ea:com.exonum.binding... -jar …
```

Added jacoco defaults

---

pom.xml

"report" goal bound to post-integration-test phase overwrote
the previous report from unit tests bound to "prepare-package"
phase. It happened because both execution of the *same* goal
used the same output directory.
---

Fix coverage reporting:

---

exonum-java-binding-common/src/test/java/com/exonum/binding/common/serialization/UInt32SerializerTest.java

Extend the tests of invalid values (*failing*, must be fixed). @bullet-tooth , please extend the tests for 64 values also. Probably, sources may be re-used between sint32 and uint32 (same for 64).
---
See: https://jira.bf.local/browse/ECR-2380

Add some tests of invalid varints

---

exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/list/ListProofStructureValidator.java
exonum-java-binding-common/src/test/java/com/exonum/binding/common/proofs/list/ListProofStructureValidatorTest.java

- Add minor improvements to the validator
- Add a failing test of missing check:
The validator currently allows null right nodes in any branch node, however, only the rightmost branch on the *deepest* branch level can have a missing right child.
---
See: https://jira.bf.local/browse/ECR-2490

Add some minor improvements to the validator

---

exonum-java-binding-common/src/main/java/com/exonum/binding/common/message/BinaryTransactionMessage.java
exonum-java-binding-common/src/main/java/com/exonum/binding/common/message/TransactionMessage.java
exonum-java-binding-common/src/test/java/com/exonum/binding/common/message/BinaryTransactionMessageTest.java

Use remaining instead of limit to represent the size. Although in these particular cases they are the same, it more clearly communicates _what_ is available to read from the buffer.
Also, extract duplicated expressions in a field.
Make BinaryTransactionMessage package-private as it is already
non-instantiable directly.
---
See: https://jira.bf.local/browse/ECR-2377

ECR-2377 improvements

---

exonum-java-binding-core/rust/src/storage/core_schema.rs
exonum-java-binding-core/rust/src/storage/mod.rs

Implement the native methods of CoreSchemaProxy: nativeCreate, nativeFree, nativeGetHeight, nativeGetLastBlock. 
---
See: https://jira.bf.local/browse/ECR-2540

Implement the native methods of CoreSchemaProxy [ECR-2540]

---

.travis.yml
exonum-java-binding-common/src/main/java/com/exonum/binding/common/message/Message_Builder2.java
pom.xml

- Update dependencies for Java 11 support
- Build the project on OpenJDK 11
The project remains (for now) compatible with 8.
---

Update dependencies, build on 11

---

exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs

A tiny improvement in order to avoid workaround with empty messages while throwing an exception.
---
See: https://jira.bf.local/browse/ECR-2502

Improvement in throwing exception with no message [ECR-2502]

---

exonum-java-binding-core/rust/src/storage/core_schema.rs

The method returns the configuration for the latest height of the blockchain serialized to JSON string.
---
See: https://jira.bf.local/browse/ECR-2646

Implemented native method for CoreSchema#getActualConfiguration [ECR-2646].

---

exonum-java-binding-core/rust/Cargo.lock
exonum-java-binding-core/rust/integration_tests/Cargo.toml
exonum-java-binding-core/rust/integration_tests/src/mock/service.rs
exonum-java-binding-core/rust/integration_tests/tests/service_proxy.rs
exonum-java-binding-core/rust/src/proxy/service.rs
exonum-java-binding-fakes/pom.xml
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/MockInteraction.java
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/TestException.java
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/UserServiceAdapterMockBuilder.java
exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/services/service/TestService.java

---
See: https://jira.bf.local/browse/ECR-2454

Implement block commited event translation from Rust to Java [ECR-2454]

---

exonum-java-binding-core/src/main/java/com/exonum/binding/proxy/NativeHandle.java
exonum-java-binding-core/src/test/java/com/exonum/binding/proxy/AbstractCloseableNativeProxyTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/proxy/NativeHandleTest.java

NativeHandle preserve the original value of the handle after invalidation.
---
See: https://jira.bf.local/browse/ECR-2528

Improve NativeHandle debuggability [ECR-2528]

---

exonum-java-binding-common/src/test/java/com/exonum/binding/common/proofs/map/DbKeyCommonPrefixParameterizedTest.java
exonum-java-binding-common/src/test/java/com/exonum/binding/common/proofs/map/DbKeyComparisonParameterizedTest.java
exonum-java-binding-common/src/test/java/com/exonum/binding/common/proofs/map/KeyBitSetIsPrefixParameterizedTest.java

- Remove some redundant parameters from the tests. `KeyBitSetIsPrefixParameterizedTest` is left as is for now, as it would require a more significant refactoring.
- Test that the comparator is symmetric
---
See: https://jira.bf.local/browse/ECR-2419

Improve parameterized tests [ECR-2419]

---

.travis.yml

Compilation of every tool is be broken on 1.27.2.
See ECR-2750
---

Ignore all rust checks:

---

exonum-java-binding-core/findbugs-exclude.xml
exonum-java-binding-core/src/main/java/com/exonum/binding/blockchain/Block.java
exonum-java-binding-core/src/main/java/com/exonum/binding/storage/indices/ValueSetIndexProxy.java
exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/BlockTest.java

As SHA-256 already has a good distribution, there is no need
to include all fields in hashCode computation.
---
See: https://jira.bf.local/browse/ECR-2739

Use first four bytes of SHA-256 hash as the Block#hashCode [ECR-2739]

---

exonum-java-binding-cryptocurrency-demo/Readme.md
exonum-java-binding-cryptocurrency-demo/frontend/src/plugins/blockchain.js

Set proper Content-Type header when submitting binary txs
---
See: https://jira.bf.local/browse/ECR-2714

ECR-2714 [FE] Set proper Content-Type header when submitting binary txs

---

exonum-java-binding-core/src/main/java/com/exonum/binding/blockchain/CoreSchemaProxy.java

Height in getBlockTransactions was checked incorrectly.
---
See: https://jira.bf.local/browse/ECR-2760

Fix getBlockTransactions bug [ECR-2760]

---

exonum-java-binding-core/src/main/java/com/exonum/binding/blockchain/CoreSchemaProxy.java
exonum-java-binding-core/src/main/java/com/exonum/binding/blockchain/TransactionResult.java
exonum-java-binding-core/src/main/java/com/exonum/binding/blockchain/serialization/TransactionResultSerializer.java
exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/TransactionResultTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/serialization/TransactionResultSerializerTest.java

It is believed to be slightly easier to use in cases where
an empty description is just fine: conversion to JSON, using in log
messages.
---
See: https://jira.bf.local/browse/ECR-2748

Use an empty string as 'no description' [ECR-2748]

---

exonum-java-binding-core/checkstyle-suppressions.xml
exonum-java-binding-core/src/main/java/com/exonum/binding/blockchain/Block.java
exonum-java-binding-core/src/main/java/com/exonum/binding/blockchain/Blockchain.java
exonum-java-binding-core/src/main/java/com/exonum/binding/blockchain/CoreSchemaProxy.java
exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/BlockchainIntegrationTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/BlockchainTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/Blocks.java
exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/CoreSchemaProxyIntegrationTest.java
exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/serialization/BlockSerializerTest.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java

- `containsBlock(Block) -> boolean`,
- `getBlock(long height) -> Block`
Also, rename `getBlock(HashCode)` to `findBlock` so that it is clearer that there might not be a block with the given hash.
---
See: https://jira.bf.local/browse/ECR-2738

Add more blockchain accessors [ECR-2738]

---

exonum-java-binding-common/src/main/java/com/exonum/binding/common/configuration/ConsensusConfiguration.java
exonum-java-binding-common/src/test/java/com/exonum/binding/common/serialization/json/StoredConfigurationGsonSerializerTest.java
exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/ApiControllerIntegrationTest.java

Consensus Configuration parameter round_timeout renamed to first_round_timeout.
---
See: https://jira.bf.local/browse/ECR-2778

[ECR-2778] round_timeout renamed to first_round_timeout.

---

exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxHistoryTest.java

`contains` turns out to take either a vararg of elements or matchers;
or a list of _matchers_ (but not the list of _elements_, as used to be
passed). Therefore, the code matched the first element against
a _list_, not its first element.
---

Fix the matchers:

---

.travis.yml
CHANGELOG.md
exonum-java-binding-core/rust/ejb-app/TUTORIAL.md
exonum-java-binding-core/rust/integration_tests/src/vm.rs
exonum-java-binding-core/rust/integration_tests/tests/service_runtime.rs
exonum-java-binding-core/rust/src/runtime/cmd.rs
exonum-java-binding-core/rust/src/runtime/config.rs
exonum-java-binding-core/rust/src/runtime/java_service_runtime.rs

---
See: https://jira.bf.local/browse/ECR-2556

Allow setting JVM arguments at node runtime [ECR-2556].

---

CHANGELOG.md
exonum-java-binding-common/src/main/java/com/exonum/binding/common/configuration/StoredConfiguration.java
exonum-java-binding-common/src/test/java/com/exonum/binding/common/message/MessageTest.java
exonum-java-binding-core/src/main/java/com/exonum/binding/service/Node.java
exonum-java-binding-core/src/main/java/com/exonum/binding/service/NodeFake.java
exonum-java-binding-core/src/main/java/com/exonum/binding/service/NodeProxy.java
exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java

Change signature of Node#getPublicKey from byte[] to PublicKey.
---
See: https://jira.bf.local/browse/ECR-2758

Change signature of Node#getPublicKey from byte[] to PublicKey [ECR-2758]

---

.travis.yml
.travis/run_travis_job.sh
exonum-java-binding-core/pom.xml
exonum-java-binding-core/rust/integration_tests/tests/service_proxy.rs
exonum-java-binding-core/rust/integration_tests/tests/service_runtime.rs
exonum-java-binding-core/rust/integration_tests/tests/transaction_proxy.rs
tests_profile

Updated to the latest stable Rust version and temporarily disabled some of the native tests that fail on Travis CI.
---

Update to stable Rust and disable native tests

---

.travis.yml
exonum-java-binding-core/rust/integration_tests/benches/jni_cache.rs
exonum-java-binding-core/rust/integration_tests/src/executor.rs
exonum-java-binding-core/rust/integration_tests/src/vm.rs
exonum-java-binding-core/rust/integration_tests/tests/jni_cache.rs
exonum-java-binding-core/rust/integration_tests/tests/jni_cache_not_initialized.rs
exonum-java-binding-core/rust/integration_tests/tests/service_proxy.rs
exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs

Fixed issue with initialization of JNI cache in integration tests. Refactoring to make the code cleaner.
---
See: https://jira.bf.local/browse/ECR-2794

Fixed broken native tests [ECR-2794].

---

exonum-java-binding-core/src/main/java/com/exonum/binding/service/Node.java

Clarify that if an unknown tx is submitted through Node#submitTx,
it is verified by each node when adding to their transaction pools.
---
See discussion in: https://jira.bf.local/browse/ECR-2793

Improve the documentation: [ECR-2793]

---

exonum-java-binding-core/rust/integration_tests/tests/transaction_proxy.rs
exonum-java-binding-core/rust/src/proxy/transaction.rs

Implemented JSON serialization of transactions (previously was removed after switching to separate messages & exonum 0.10)
---
See: https://jira.bf.local/browse/ECR-2790

Added JSON serialization to transaction [ECR-2790]

---

exonum-java-binding/core/rust/src/storage/proof_map_index.rs

No more checking of map proof before sending it to Java.
Also renamed `create_java_unchecked_flat_map_proof` to `create_java_unchecked_map_proof`
---
See: https://jira.bf.local/browse/ECR-1802

Do not check proofs when sending them to Java [ECR-1802]

---

.travis.yml
.travis/run_travis_job.sh
exonum-java-binding/core/rust/integration_tests/src/mock/service.rs
exonum-java-binding/core/rust/src/lib.rs
exonum-java-binding/core/rust/src/proxy/executors.rs
exonum-java-binding/core/rust/src/proxy/transaction.rs
exonum-java-binding/core/rust/src/runtime/cmd.rs
exonum-java-binding/core/rust/src/storage/proof_list_index.rs
exonum-java-binding/core/rust/src/storage/proof_map_index.rs
exonum-java-binding/core/rust/src/utils/mod.rs

---
See: https://jira.bf.local/browse/ECR-2750

Reenabled Rust checks [ECR-2750]

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/src/proxy/service.rs

Ejb points to the minimal required version of jni.rs from the `master` that introduces JEnv#clone().
---
See: https://jira.bf.local/browse/ECR-2491

Pointing EJB to the jni.rs from master

---

.travis.yml

Seems [the issue with random integration test failure](https://jira.bf.local/browse/ECR-1734) is not reproducible anymore.
---
See: https://jira.bf.local/browse/ECR-1734

Removed the `allow_failures` section from Travis config [ECR-1734]

---

exonum-java-binding/pom.xml
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
exonum-java-binding/testing/pom.xml
exonum-java-binding/time-service/pom.xml
exonum-light-client/pom.xml

Use a single aggregate dependency on JUnit 5 junit-jupiter-api
and junit-jupiter-params + junit-jupiter-engine from 5.4.0 release.
https://junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.4.0
---

Use a single aggregate dependency on JUnit 5

---

exonum-java-binding/core/src/main/java/com/exonum/binding/blockchain/CoreSchemaProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/service/Schema.java
exonum-java-binding/core/src/main/java/com/exonum/binding/service/Service.java
exonum-java-binding/core/src/test/java/com/exonum/binding/blockchain/serialization/TransactionLocationSerializerTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/blockchain/serialization/TransactionResultSerializerTest.java
exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/CryptocurrencySchema.java
exonum-java-binding/pom.xml
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/ApiController.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaSchema.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MySchema.java
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MyTransactionConverter.java
pom.xml

Various minor changes throughout the project.
---

Minor EJB fixes

---

exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/ServiceId.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/ServiceIdTest.java

That’s a smallish part of ECR-2953 that can be reviewed. See also the [design page](https://wiki.bf.local/display/EJB/Multiple+Java+Services+Design#MultipleJavaServicesDesign-%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%BE%D0%B2:%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%D0%B5%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D1%8B).
---
See: https://jira.bf.local/browse/ECR-2953

Add ServiceId [ECR-2953]

---

.travis.yml
CONTRIBUTING.md
exonum-java-binding/core/pom.xml
exonum-java-binding/core/rust/ejb-app/TUTORIAL.md
exonum-java-binding/core/rust/ejb-app/start_cryptocurrency_node.sh
exonum-java-binding/core/rust/ejb-app/start_qa_node.sh
exonum-java-binding/cryptocurrency-demo/Readme.md
exonum-java-binding/tests_profile

Switching back to Rust 1.32.0 until bugs introduced by latest compiler version fixed.
---

Temporary switching back to Rust 1.32.0

---

exonum-java-binding/qa-service/pom.xml

It is a quick-fix so that time oracle appears on the classpath of QA service;
once packaging is here the time oracle must be included in the application and be 'provided'-scoped in any service.
---
See: https://jira.bf.local/browse/ECR-2987

Make time oracle a compile-scoped dependency of QA service [ECR-2987]

---

exonum-java-binding/fake-service/pom.xml
exonum-java-binding/fake-service/src/main/java/com/exonum/binding/fakeservice/FakeService.java
exonum-java-binding/fake-service/src/main/java/com/exonum/binding/fakeservice/FakeServiceModule.java
exonum-java-binding/fake-service/src/test/java/com/exonum/binding/fakeservice/FakeServiceModuleTest.java
exonum-java-binding/fakes/src/main/java/com/exonum/binding/fakes/services/service/TestService.java
exonum-java-binding/pom.xml

Add a fake-service for integration tests of artifact loading
(native and, potentially, Java).
Also, remove explicit scope for Guava as it affects the dependency
resolution (overriding the *scope* of Guava and its transitive dependencies to always be `compile`, even if the dependent artifact is in `provided`). See https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies for details
---
See: https://jira.bf.local/browse/ECR-3009

 Add a fake-service for tests [ECR-3009]

---

exonum-java-binding/testing/pom.xml
exonum-java-binding/testing/src/main/java/com/exonum/binding/test/runtime/ServiceArtifactBuilder.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/ServiceArtifactBuilderTest.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/TestService.java

Add ServiceArtifactBuilder allowing to create at runtime
Exonum Service artifacts, including malformed to be able
to test error handling.
---
See: https://jira.bf.local/browse/ECR-3014

Add ServiceArtifactBuilder [ECR-3014]

---

exonum-java-binding/testing/pom.xml
exonum-java-binding/testing/src/main/java/com/exonum/binding/test/runtime/ServiceArtifactBuilder.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/ServiceArtifactBuilderSmokeIntegrationTest.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/ServiceArtifactBuilderTest.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/testplugin/TestPlugin.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/testplugin/TestServiceExtension.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/testplugin/TestServiceExtensionImpl.java

Test that the artifact produced by the ServiceArtifactBuilder can
be properly loaded by PF4J.
---
See: https://jira.bf.local/browse/ECR-3014

Add a ServiceArtifactBuilder smoke integration test [ECR-3014]

---

exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/EvilPluginFailingToStart.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/Pf4jServiceLoaderIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/TestServiceModule1.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/TestServiceModule2.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/TestServiceModuleInaccessibleCtor.java
exonum-java-binding/testing/src/main/java/com/exonum/binding/test/runtime/ServiceArtifactBuilder.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/ServiceArtifactBuilderSmokeIntegrationTest.java
exonum-java-binding/testing/src/test/java/com/exonum/binding/test/runtime/ServiceArtifactBuilderTest.java

Replace mock-based Pf4jServiceLoader tests with integration tests
that use a real PluginManager.
---
See: 
- https://jira.bf.local/browse/ECR-2969
- #783

Replace mock-based unit tests with integration tests [ECR-2969]

---

exonum-light-client/src/main/java/com/exonum/client/ExonumClient.java
exonum-light-client/src/main/java/com/exonum/client/ExonumHttpClient.java
exonum-light-client/src/main/java/com/exonum/client/request/BlockFilteringOption.java
exonum-light-client/src/main/java/com/exonum/client/request/BlockTimeOption.java
exonum-light-client/src/test/java/com/exonum/client/ExonumHttpClientBlocksIntegrationTest.java

---
LC refactoring:
* Removed time option from `getLastBlock`
* Replaced boolean flags by enums
See: https://jira.bf.local/browse/ECR-2994

[ECR-2994] LC: Booleans replaced by enums

---

exonum-java-binding/bom/pom.xml
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/ServiceModule.java

Update the archetype so that it includes the configuration
to build an Exonum service artifact — a JAR with some metadata.
---
See: https://jira.bf.local/browse/ECR-3006

Update the archetype to work with multiple services [ECR-3006]

---

exonum-java-binding/core/src/test/java/com/exonum/binding/service/adapters/UserTransactionAdapterTest.java

A mock of an Exception will not have a stackTrace, which is forbidden
by `#getStackTrace` specification, hence, implementations are fine
not checking for it being `null`:
```
[INFO] Running com.exonum.binding.service.adapters.UserTransactionAdapterTest
2019-03-26 16:46:12,814 main ERROR An exception occurred processing Appender ListAppender java.lang.NullPointerException
at org.apache.logging.log4j.core.impl.ThrowableProxyHelper.toExtendedStackTrace(ThrowableProxyHelper.java:87)
```
---

Fix the NPE in log4j code when mocks of Exceptions are used:

---

exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/FrameworkModule.java
exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/JarPluginManager.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/JarPluginManagerSmokeIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/Pf4jServiceLoaderIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/Pf4jServiceLoaderIntegrationTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/Pf4jServiceLoaderWithDefaultIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/Pf4jServiceLoaderWithJarIntegrationTest.java
exonum-java-binding/pom.xml

Override the operations in DefaultPluginManager that produce
services that support both types of plugins (ZIP and JARs) or that
do not make sense with JARs or our use cases.
That allows to reduce the number of I/O operations during plugin
loading (as of 2.6.x, ZIP has higher priority than JAR) and the number
of redundant log messages.
If no longer needed, JarPluginManager class can be replaced with
a DefaultPluginManager — Pf4jServiceLoader is continuously tested against it.
---
See: https://jira.bf.local/browse/ECR-3066

Use a PluginManager tailored for JARs [ECR-3066]:

---

exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/FrameworkModule.java
exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/RuntimeModule.java
exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/ServiceRuntime.java

Make the ServiceRuntime actually thread-safe without reliance
on ServiceLoader thread-safety, because ServiceRuntime is a Singleton
and *may* be injected into other objects. That does not happen
currently; nor the ServiceRuntime is used in a multi-threaded
context, hence this feature is provided to avoid possible
synchronization errors if it does happen in the future (e.g.,
if in dynamic services the operations on ServiceRuntime are invoked
on different threads).
The other runtime-specific binding are put in a private module,
i.e., they are inaccessible to satisfy bindings from other
modules or from injector directly.
---
See: https://jira.bf.local/browse/ECR-3065

Make the ServiceRuntime actually thread-safe [ECR-3065]:

---

exonum-java-binding/core/rust/src/runtime/java_service_runtime.rs

Added human-readable error descriptions for JNI codes that weren't covered in the jni.rs lib for the result of JVM creation.
---
See: https://jira.bf.local/browse/ECR-2841

Improved error message for invalid arguments [ECR-2841]

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/ejb-app/Cargo.toml
exonum-java-binding/core/rust/ejb-app/src/main.rs
exonum-java-binding/core/rust/ejb-app/start_cryptocurrency_node.sh
exonum-java-binding/core/rust/ejb-app/start_qa_node.sh
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaSchema.java

Enabled env_logger for EJB App & update scripts for Exonum 0.11
---

Packaging fixups

---

exonum-java-binding/core/src/main/java/com/exonum/binding/storage/indices/package-info.java
exonum-java-binding/pom.xml
exonum-light-client/pom.xml

Update checkstyle to 8.19 and update the issues that were fixed in it - `Javadoc for package-info file is not validated.` https://checkstyle.org/releasenotes.html#Release_8.19
---

Update checkstyle to 8.19

---

CONTRIBUTING.md
exonum-java-binding/core/pom.xml
exonum-java-binding/package_app.sh
exonum-java-binding/packaging/pom.xml
exonum-java-binding/pom.xml
exonum-java-binding/time-oracle/pom.xml

Added new release mode for `package_app.sh` script.
---
See: https://jira.bf.local/browse/ECR-2290

EJB App release build [ECR-2290]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/json/StoredConfigurationGsonSerializerTest.java
exonum-java-binding/core/rust/exonum-java/start_cryptocurrency_node.sh
exonum-java-binding/core/rust/exonum-java/start_qa_node.sh
exonum-java-binding/core/src/main/java/com/exonum/binding/service/Service.java
exonum-java-binding/core/src/main/java/com/exonum/binding/service/adapters/UserServiceAdapter.java
exonum-java-binding/core/src/test/java/com/exonum/binding/service/adapters/UserServiceAdapterTest.java
exonum-java-binding/cryptocurrency-demo/frontend/src/plugins/blockchain.js
exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/CryptocurrencyService.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaService.java

Change it from "/api" to "/api/services" for consistency
with Exonum Core.
Also, change service names:
- "cryptocurrency-demo-service" -> "cryptocurrency-demo"
- "ejb-qa-service" -> "qa"
---
See: https://jira.bf.local/browse/ECR-3042

Update the service API prefix [ECR-3042]:

---

exonum-java-binding/core/rust/Cargo.lock

- actix-web v0.7.18 -> v0.7.19
- aho-corasick v0.6.10 -> v0.7.3
- arc-swap v0.3.7 -> v0.3.9
- backtrace v0.3.14 -> v0.3.15
- bit-vec v0.5.0 -> v0.5.1
- bitcoin_hashes v0.3.1 -> v0.3.2
- bytes v0.4.11 -> v0.4.12
- cc v1.0.31 -> v1.0.35
- cfg-if v0.1.6 -> v0.1.7
- clap v2.32.0 -> v2.33.0
- combine v3.6.7 -> v3.8.1
- crc32fast v1.1.2 -> v1.2.0
- Removed crossbeam v0.6.0
- crossbeam-deque v0.6.3 -> v0.7.1
- (+) crossbeam-queue v0.1.2
- either v1.5.1 -> v1.5.2
- flate2 v1.0.6 -> v1.0.7
- futures v0.1.25 -> v0.1.26
- h2 v0.1.16 -> v0.1.17
- http v0.1.16 -> v0.1.17
- hyper v0.12.24 -> v0.12.25
- hyper-tls v0.3.1 -> v0.3.2
- libc v0.2.49 -> v0.2.51
- linked-hash-map v0.4.2 -> v0.5.2
- lru-cache v0.1.1 -> v0.1.2
- nom v4.2.1 -> v4.2.3
- openssl v0.10.18 -> v0.10.20
- openssl-sys v0.9.41 -> v0.9.43 …

Update Rust dependencies:

---

exonum-java-binding/core/rust/Cargo.lock

A problem with application was discovered in our system tests:
```
ejb_1_1d90542c7589 | ./exonum-java: symbol lookup error: ./exonum-java: undefined symbol: _ZN134_$LT$java_bindings..runtime..service_factory_adapter..JavaServiceFactoryAdapter$u20$as$u20$exonum..helpers..fabric..ServiceFactory$GT$7command17h55cdb2ff9ab423f7E
```
This reverts commit 32007a56
---

Revert "Update Rust dependencies: (#825)"

---

.travis.yml
exonum-java-binding/cryptocurrency-demo/Readme.md
exonum-light-client/pom.xml

As OpenJDK 11 is no longer updated, it was decided to cease testing
on it — see ECR-3088
---
See: https://jira.bf.local/browse/ECR-3088

Build on the latest OpenJDK [ECR-3088]

---

exonum-java-binding/pom.xml
exonum-light-client/pom.xml

Applied the fix from https://bugs.openjdk.java.net/browse/JDK-8212233
Also, updated the plugin to the most recent version
---

Fix building Javadocs on 12:

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/src/lib.rs
exonum-java-binding/core/rust/src/testkit/mod.rs

Implemented native methods for Testkit support:
- nativeCreateTestKit()
- nativeCreateSnapshot()
- nativeCreateBlockWithTransactions()
- nativeCreateBlock()
- nativeGetEmulatedNode()
---
See: https://jira.bf.local/browse/ECR-3052

Implement native part of the TestKit [ECR-3052]

---

exonum-java-binding/pom.xml
exonum-light-client/pom.xml

Add links to EJB modules that have dependent modules,
so that the Javadocs for consuming modules (e.g., time-oracle)
have correct links to Javadocs of these modules
(common and core).
This requires a two-step publication of Javadocs (which
we already do to check correctness of other outgoing links).
An alternative of aggregating all Javadocs may be considered
in the future: it works alright, but loses information about
which package belongs to which module.
Websites hosting javadocs of our external dependencies do
not seem to work with javadoc tool (checked guava at javadoc.io
and vertx at github.io).
---
See: 
- https://jira.bf.local/browse/ECR-3018

Add links to EJB modules [ECR-3018]:

---

exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/ApiController.java

Remove the body handler as the cryptocurrency no longer
accepts POST requests (since 0.4.0, when transactions are accepted
by the core).
---

Remove the HTTP body handler:

---

exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/ClassLoadingScopeChecker.java
exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/Pf4jServiceLoader.java
exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/RuntimeModule.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/ClassLoadingScopeCheckerTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/runtime/Pf4jServiceLoaderIntegrationTestable.java
exonum-java-binding/pom.xml

Check that no copies of application libraries are included in the
service artifact during artifact loading. It helps to prevent
errors in build definitions when a dependency does not have
'provided' scope set, as recently discovered ECR-3091.
The present version cannot check if time-oracle is included
because it is not available on the core classpath.
---
See: 
- https://jira.bf.local/browse/ECR-3046
- https://jira.bf.local/browse/ECR-3091

Check no copies of application libraries in artifact [ECR-3046]:

---

exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/transactions/CreateCounterTx.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/transactions/IncrementCounterTx.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/transactions/TransactionError.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/transactions/CreateCounterTxIntegrationTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/transactions/IncrementCounterTxIntegrationTest.java

Migrated CreateCounterTx and IncrementCounterTx to use
TransactionExecutionError when their preconditions are violated
(e.g., when a non-existent counter is incremented). In such cases
transactions will be committed with the given error code instead of
successful completion.
---
See: https://jira.bf.local/browse/ECR-3099

Update error handling in QA service transactions [ECR-3099]:

---

exonum-java-binding/core/rust/exonum-java/TUTORIAL.md
exonum-java-binding/core/rust/src/runtime/cmd.rs

Specified default value for the `--ejb-log-config-path`.
---
See: https://jira.bf.local/browse/ECR-3030

Make `ejb-log-config-path` parameter actually optional [ECR-3030]

---

.travis.yml

Disable builds on JDK 12 temporarily because Travis
fails to download it.
---

Disable builds on JDK 12 temporarily

---

exonum-light-client/pom.xml
exonum-light-client/src/main/java/com/exonum/client/response/TransactionResponse.java
exonum-light-client/src/test/java/com/exonum/client/response/TransactionResponseTest.java

---
See: https://jira.bf.local/browse/ECR-3100
Do not use `getExecutionResult` for in-pool transactions such as it throws an exception

[ECR-3100] Fix tx response methods that use tx result

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/pom.xml
exonum-java-binding/core/src/test/java/com/exonum/binding/storage/database/MemoryDbIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/storage/database/NativeResourceManagerIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/storage/indices/BaseIndexGroupTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/storage/indices/BaseIndexProxyTestable.java
exonum-java-binding/package_app.sh
exonum-java-binding/pom.xml
exonum-java-binding/testing/src/main/java/com/exonum/binding/test/RequiresNativeLibrary.java
exonum-java-binding/time-oracle/src/test/java/com/exonum/binding/time/TimeSchemaProxyIntegrationTest.java

It was discovered in ECR-2899 that the Java ITs requiring the native
library work on master in the following cases (see the document
for more details):
- librocksdb4.1 is installed
- librocksdb5.17 is installed
- no librocksdb is installed.
Therefore this PR:
- Enables all Java ITs requiring the native library on Linux
- Removes the mechanism disabling core Java ITs on Linux
- Annotates core ITs with @RequiresNativeLibrary (currently has no
effect, but can be used to filter them in the future).
---
See:
- https://jira.bf.local/browse/ECR-2899
- https://jira.bf.local/browse/ECR-942

Re-enable Java ITs on Linux [ECR-942]:

---

exonum-java-binding/app/pom.xml
exonum-java-binding/app/src/main/java/com/exonum/binding/app/ServiceRuntimeBootstrap.java
exonum-java-binding/app/src/test/java/com/exonum/binding/app/ServiceRuntimeBootstrapIntegrationTest.java
exonum-java-binding/core/rust/src/runtime/java_service_runtime.rs
exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/FrameworkModule.java
exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/RuntimeModule.java
exonum-java-binding/fakes/src/test/java/com/exonum/binding/fakes/services/ServiceArtifactsIntegrationTest.java
exonum-java-binding/packaging/pom.xml
exonum-java-binding/pom.xml

Add an internal Java app module that has all dependencies of the native
application (currently, core + time-oracle and their transitives).
Move ServiceRuntimeBootstrap to app module to be able to configure
it using types from any _application_ dependency (i.e., time oracle).
Moves the dependency reference classes to app module to be able to
add time oracle as forbidden to be included in the service artifact
(and adds it as such).
Specify the dependencies on app as JAR (default) to simplify the configuration.
---
See:
- https://jira.bf.local/browse/ECR-3114
- https://jira.bf.local/browse/ECR-3115

Add java app module & check time oracle is not included [ECR-3114, ECR-3115]

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/src/lib.rs
exonum-java-binding/core/rust/src/testkit/mod.rs
exonum-java-binding/core/rust/src/testkit/time_provider.rs

JavaTimeProvider proxy implements TimeProvider trait and can be used to setup needed Time Service state in tests
---
See: https://jira.bf.local/browse/ECR-3053

Implement Time Service support for TestKit [ECR-3053]

---

.travis.yml

The service runtime test again got flaky. As previously on 10 and 11 (ECR-1734), the test itself passes, but the process terminates with segmentation fault:
```
error: process didn't exit successfully: `/home/travis/build/exonum/exonum-java-binding/exonum-java-binding/core/rust/target/debug/deps/service_runtime_bootstrap-aa9708941300cf7a` (signal: 11, SIGSEGV: invalid memory reference)
```
First discovered in #814 
---
See: https://jira.bf.local/browse/ECR-3133

Allow build failures on JDK 12 [ECR-3133]:

---

exonum-java-binding/core/rust/Cargo.toml

This fixes release builds on Mac (though I don't even understand why)
---
See: https://jira.bf.local/browse/ECR-3072

Use rpath for release profile too [ECR-3072]

---

exonum-java-binding/core/src/main/java/com/exonum/binding/service/Service.java
exonum-java-binding/cryptocurrency-demo/Readme.md

The script had an incorrect name.
Also, add a link to the installation instruction and make some
cosmetic changes.
---
Improve createPublicApiHandlers Javadoc:
- fix endpoint name
- clarify the base path for user handlers
- specify protocol
- add link to the documentation
--- 
**Q:** That affects 0.6.0, how do we handle that? Cherry-pick and move the tag? Make 0.6.1?
---

Fix some documentation:

---

.travis.yml

... because it is already merged into master.
---
See: https://jira.bf.local/browse/ECR-3137

Removed the `multiple-services` branch from travis config [ECR-3137]

---

exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/TestKit.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java

Fix findTransactionsInPool in TestKi and add a test checking that node.submitTransaction adds transactions to the pool.

Fix findTransactionsInPool in TestKit

---

exonum-java-binding/core/rust/exonum-java/TUTORIAL.md
exonum-java-binding/core/rust/exonum-java/start_cryptocurrency_node.sh
exonum-java-binding/core/rust/exonum-java/start_qa_node.sh
exonum-java-binding/cryptocurrency-demo/Readme.md
exonum-java-binding/cryptocurrency-demo/start-cryptocurrency-demo.sh

Default unsafe port `6000` for demos has been changed to `7000`.
---
See: https://jira.bf.local/browse/ECR-3175

Changed default port from 6000 to 7000 in scripts and docs.

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/src/main/java/com/exonum/binding/util/LibraryLoader.java

Check that the loaded native library is compatible, i.e.,
has the same version as the Java library. This check is useful in
_service integration tests_ that can update their dependency
on 'exonum-java-binding-core' but not the application (that
contains the native library), or vice versa.
Requires native code to enable this check: ECR-3172
---
See: https://jira.bf.local/browse/ECR-3148

Check that the loaded native library is compatible [ECR-3148]:

---

exonum-java-binding/core/rust/integration_tests/tests/jni_cache_not_initialized.rs
exonum-java-binding/core/rust/src/utils/jni_cache.rs

Now it clearly says about JNI cache
---
See: https://jira.bf.local/browse/ECR-3086

Improved error message about JNI cache initialization [ECR-3086]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/common/src/main/java/com/exonum/binding/common/message/BinaryTransactionMessage.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/message/BinaryTransactionMessageTest.java

Include serviceId, transactionId, payload (as byte array),
and author. The signature is omitted, as the other fields of
messages (class, tags).
The output now looks like that (consistent with RawTransaction):
```
BinaryTransactionMessage{
author=93afa1b0406faff182608b04e63e10cf0237b33215de16de68c151c7ab32958c,
serviceId=127,
transactionId=1,
payload=[8, 1, 18, 32, -83, -87, 62, 57, -72, -99, 126, -106, -45, 62, -44, -17, 14, -26, 10, -127, -49, -124, 84, -107, 90, 125, -94, 34, 106, -8, 33, 0, -92, -84, 110, -84]
}
```
Also, check the class and tag of tx messages.
---
See: #893

Re-implement BinaryTransactionMessage#toString:

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/src/main/java/com/exonum/binding/transaction/RawTransaction.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java
exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/TestKit.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java

Add RawTransaction#fromMessage(TransactionMessage), which is mostly
useful in tests, where you might have a message but need to use
it in some assertions.
Also, include the whole message where appropriate (since it has proper
#toString now) and make assertions on error messages looser.
---

Add RawTransaction#fromMessage

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/package_app.sh

With this update, `ROCKSDB_STATIC` environment variable actually controls the linkage type of rocksdb library. With this variable set, we'll get binaries which are not depending on user-provided rocksdb dymanic library.
---
See: https://jira.bf.local/browse/ECR-3169

Update exonum_rocksdb [ECR-3169]

---

exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaSchemaIntegrationTest.java

Update QaSchemaIT using TestKit.
---
See: https://jira.bf.local/browse/ECR-3054

Update QaSchemaIT using TestKit [ECR-3054]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/common/src/main/java/com/exonum/binding/common/serialization/json/JsonSerializer.java
exonum-java-binding/core/src/main/java/com/exonum/binding/transaction/Transaction.java
exonum-java-binding/core/src/test/java/com/exonum/binding/transaction/TransactionTest.java

Empty string caused panic in the native code,
and, subsequently, failed request processing.
Made #info return an empty object, though, one might
argue it will be more difficult to understand
why `transactions` returns nothing. That, however,
is to be addressed *after* Dynamic Services.
---
See: https://jira.bf.local/browse/ECR-3193

Fix default Transaction#info [ECR-3193]:

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/package_app.sh

Further investigation will be done in a separated branch
---
See: https://jira.bf.local/browse/ECR-3169

Revert RocksDB update, as it ruins native tests on Linux [ECR-3169]

---

exonum-light-client/README.md

Doc links update

---

exonum-light-client/pom.xml

Add plugin versions for LC maven plugins

---

exonum-java-binding/core/rust/exonum-java/start_cryptocurrency_node.sh
exonum-java-binding/cryptocurrency-demo/start-cryptocurrency-demo.sh

Enable native logging by default in scripts starting a single
node. start_qa, launching multiple nodes, is left with
no predefined RUST_LOG.
---

Enable native logging by default:

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/src/runtime/java_service_runtime.rs

Arguments are logged with the `info` level.
---
See: https://jira.bf.local/browse/ECR-3147

Added logging of JVM arguments before JVM start [ECR-3147]

---

exonum-java-binding/common/src/test/java/com/exonum/binding/common/hash/AbstractByteHasherTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/hash/AbstractNonStreamingHashFunctionTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/hash/AbstractStreamingHasherTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/hash/FunnelsTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/hash/HashCodeTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/hash/HashTestUtils.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/hash/HashingTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/hash/MessageDigestHashFunctionTest.java

This module was imported (see 4725ab9e for details), and rarely
changes.
These tests will no longer run on `mvn test`, but still will on
`./run_all_tests.sh` or `mvn test -P ci-build`.
---

Skip hash tests in the dev environment:

---

exonum-java-binding/core/rust/src/utils/errors.rs
exonum-java-binding/core/rust/src/utils/jni_cache.rs

- Remove explicit find_class
- Cache the RuntimeException class
- Catch possible panics in JNI_OnLoad, returning an invalid
version to communicate initialization failure
---

Remove explicit find_class:

---

exonum-java-binding/core/pom.xml

Run the unit tests of the Rust library without resource-manager on CI only. Earlier it was not possible because `cargo test` used to overwrite the library *with* rm previously built by `cargo build`, which is required for subsequent Java ITs.
The current order of test actions on CI for core:
- default-test
- test-rust-lib
- test-rust-lib-no-resource-manager <-- Used to cause problems at this position
- integration-test
These tests now won't run on `mvn test`, but still will on
`./run_all_tests.sh` or `mvn test -P ci-build`.
---

Skip unit tests without resource-manager in the dev environment:

---

exonum-java-binding/cryptocurrency-demo/pom.xml
exonum-java-binding/fake-service/pom.xml
exonum-java-binding/integration-tests/pom.xml
exonum-java-binding/packaging/pom.xml
exonum-java-binding/qa-service/pom.xml
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml

---
Fixed two kinds of warnings:
- Warning in integration tests module: `[WARNING] JAR will be empty - no content was marked for inclusion!`
Added maven configuration to do not create a `jar` file because the module is not supposed to produce it.
- Warnings in assembly plugin:
```
[INFO] --- maven-assembly-plugin:3.1.1:single (package-service-artifact) @ exonum-java-binding-cryptocurrency-demo ---
[INFO] Building jar: /Users/oleg.bondar/bf/github/exonum-java-binding/exonum-java-binding/cryptocurrency-demo/target/exonum-java-binding-cryptocurrency-demo-0.6.0-artifact.jar
[WARNING] Configuration option 'appendAssemblyId' is set to false.
Instead of attaching the assembly file: /Users/oleg.bondar/bf/github/exonum-java-binding/exonum-java-binding/cryptocurrency-demo/target/exonum-java-binding- …
```

Fix warnings during the build

---

.travis.yml
CONTRIBUTING.md
exonum-java-binding/core/pom.xml
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/integration_tests/src/vm.rs
exonum-java-binding/core/rust/src/proxy/node.rs
exonum-java-binding/tests_profile

Fixed the issue with double linking with dynamic `java_bindings` library on Mac that caused to duplicate static storage for the `resource-manager` module.
---
See: https://jira.bf.local/browse/ECR-3073

Fix issue with stable Rust compiler (> 1.32.0) [ECR-3073]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/rust/src/proxy/node.rs
exonum-java-binding/core/src/main/java/com/exonum/binding/service/Node.java
exonum-java-binding/core/src/main/java/com/exonum/binding/service/TransactionSubmissionException.java
exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/NodeProxyIntegrationTest.java

As it can occur for several reasons (not only because of
an invalid tx submitted by user), its type must communicate that.
---
See: https://jira.bf.local/browse/ECR-3190

Rename InvalidTransactionException [ECR-3190]:

---

.travis/run_travis_job.sh

The Mac builds are already slow, and Linux builds no longer skip
any tests.
---
See: https://jira.bf.local/browse/ECR-3135

Move Coveralls reporting to Linux build: [ECR-3135]

---

.travis.yml

The flaky test no longer runs at all (see abf2d850).
This reverts commit 8bdd31bd
---

Disallow build failures on JDK 12 [ECR-3133]:

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MySchema.java
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MyService.java
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MyTransactionConverter.java
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/ServiceModule.java
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/test/java/ServiceModuleTest.java
exonum-java-binding/service-archetype/src/test/resources/projects/archetype.properties
exonum-java-binding/service-archetype/src/test/resources/projects/goal.txt

Use ${package} instead of ${groupId} to allow to override it
during project configuration.
`package` parameter has a default equal to `groupId`, but it is
reasonable to allow to override it.
Also:
- Set realistic values for IT project properties
- Run `verify` so that the IT involves packaging the service
archetype.
---

Use 'package' instead of 'groupId' to allow to override it.

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/transport/VertxServer.java
exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/ApiControllerTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ApiControllerIntegrationTest.java
exonum-light-client/src/main/java/com/exonum/client/ExonumHttpClient.java

Fix usages of deprecated Router#accept. According to its Javadoc:
> This method is now deprecated you can use this object directly as
a request handler, which means there is no need for a method reference
anymore.
Fix usages of deprecated RequestBody#create. According to its Javadoc:
> Moved to extension function. Put the 'content' argument first to fix Java
---

Fix deprecations

---

.travis/run_travis_job.sh

Enable Maven batch mode, which disables the colour output and, hopefully, disables downloading
progress output.
Fixes the issue on Travis when the Travis log size is exceeded when
the build cache is cleared and Maven needs to download all
the dependencies.
---

Fix Travis builds exceeding the log size

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Node.java
exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/TestKit.java
exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/TestKitExtension.java

Fix some minor Javadoc issues.
In `Node` I removed `@throws IllegalStateException if the node proxy is closed` as it's not applicable to `NodeFake`.

Minor Javadoc fixes

---

exonum-java-binding/common/src/main/java/com/exonum/binding/common/blockchain/TransactionLocation.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/CheckedListProof.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/map/CheckedMapProof.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Service.java
exonum-java-binding/generate-javadocs.sh
exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/EmulatedNode.java
exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/TestKit.java

- Fix broken Javadocs.
- Also add a script to generate aggregated Javadocs
for published modules. As each has its unique root package,
it is easier to see which class (or package) is in which module.
The links are to be changed in all projects as part of the release procedure: https://wiki.bf.local/display/EJB/Java+Binding+0.7.0+Release+Checklist (@MakarovS)
---
See: https://jira.bf.local/browse/ECR-3329

Fix Javadocs and implement their aggregation [ECR-3329]:

---

exonum-java-binding/pom.xml
exonum-light-client/pom.xml

Remove links needed previously to link types between modules,
published separately.
Light client will have to update its link to the new one once
it migrates to Exonum Java 0.7.x.
---
See: https://jira.bf.local/browse/ECR-3329

Remove no longer needed Javadoc links [ECR-3329]

---

exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseListIndexProxyGroupTestable.java

Fix variable names:

---

exonum-java-binding/core/pom.xml
exonum-java-binding/generate-javadocs.sh
exonum-java-binding/package_app.sh

Clean and install the modules so that it works when
the local repo does not contain the artifacts with a newly set
version.
Also rename `doNotBuildRustLib` property to more usual
skip\<action>: `skipRustLibBuild`
---

Improve the script generating Javadocs:

---

CONTRIBUTING.md
exonum-java-binding/CHANGELOG.md
exonum-java-binding/package_app.sh

RocksDB is linked statically on Mac to avoid problems with dynamic library resolving.. It is required to set `ROCKSDB_LIB_DIR`  prior to running `package_app.sh`.
---
See: https://jira.bf.local/browse/ECR-3324

Use static rocksdb linkage on Mac [ECR-3324]

---

exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseListIndexProxyGroupTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/KeySetIndexProxyGroupIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxyGroupIntegrationTest.java

As the code iterated over a _MultiSet_ from `MultiMap#keys`
with a key for each key-value pair, it created multiple
instances of some collections.
---
See: https://jira.bf.local/browse/ECR-3347

Fix the tests creating indexes multiple times: [ECR-3347]

---

exonum-light-client/src/main/java/com/exonum/client/ExonumHttpClient.java
exonum-light-client/src/test/java/com/exonum/client/ExonumHttpClientBlocksIntegrationTest.java
exonum-light-client/src/test/java/com/exonum/client/ExonumHttpClientIntegrationTest.java
exonum-light-client/src/test/java/com/exonum/client/RecordedRequestMatchers.java

---
See: https://jira.bf.local/browse/ECR-3344
- Fixed path in `getBlockByHeight` method
- Specified exact string paths in tests

[ECR-3344] LC: Fixed block path. Specified exact path in tests

---

exonum-java-binding/benchmarks/README.md
exonum-java-binding/benchmarks/pom.xml
exonum-java-binding/pom.xml

This module is intended for:
- Faster, easier, _immediate_ experiments, that do not require installing the SuT into the local Maven repository to re-run benchmarks; and allow to re-build them in one command: `mvn package -pl benchmarks -am`
- Some benchmarks of Exonum Java operations that we would like to always keep updated and maintain with Exonum Java evolution.
It replaces neither exonum/exonum-benchmarking nor exonum/exonum-java-benchmarks.
---
See: https://jira.bf.local/browse/ECR-2383

Add the benchmarking module [ECR-2383]

---

exonum-java-binding/bom/pom.xml

Services have a dependency on JUnit 5 when generated with
the archetype, and it is unlikely anyone will go back to 4.
---

Remove Vertx JUnit 4 extension from our BOM:

---

exonum-light-client/CHANGELOG.md
exonum-light-client/README.md
exonum-light-client/pom.xml

Update docs for LC 0.3.0 release

---

exonum-light-client/CHANGELOG.md
exonum-light-client/README.md
exonum-light-client/pom.xml

LC v0.3.0 release

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/common/pom.xml
exonum-java-binding/common/src/main/java/com/exonum/binding/common/crypto/CryptoFunctions.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/crypto/Ed25519CryptoFunction.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/crypto/Ed25519CryptoFunctionTestable.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/crypto/Ed25519CryptoFunctionWithBundledTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/crypto/Ed25519CryptoFunctionWithSystemSodiumTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/crypto/Forked.java

That allows the users to benefit from the system libsodium
whenever it is available (it always is when the app is run,
but might not be in other usages).
---
See: https://jira.bf.local/browse/ECR-3288

Use system sodium in the crypto function by default: [ECR-3288]

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/proxy/CancellableCleanAction.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/proxy/CleanAction.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/proxy/ProxyDestructor.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Fork.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/MemoryDb.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/proxy/CleanerTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/proxy/DefaultCleanActionTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/proxy/ProxyDestructorTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/ForkIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/MemoryDbIntegrationTest.java

Support conversion of Fork into Patch:
Add Fork into Patch conversion so that the changes can be applied
to the MerkleDB database. This conversion consumes the original
fork object, therefore, it is needed to support 'native peer ownership
transfer' from Java to native.
---
See:
- https://jira.bf.local/browse/ECR-3364
- #1024

Support conversion of Fork into Patch [ECR-3364]

---

exonum-java-binding/core/rust/src/storage/key_set_index.rs
exonum-java-binding/core/rust/src/storage/map_index.rs
exonum-java-binding/core/rust/src/storage/proof_map_index.rs
exonum-java-binding/core/rust/src/storage/value_set_index.rs

Implemented JNI methods for `.size()` and `.isEmpty()` methods of indexes:
- `ProofMapIndex`
- `MapIndex`
- `KeySetIndex`
- `ValueSetIndex`
---
See: https://jira.bf.local/browse/ECR-3317

Implemented JNI methods for new methods of indexes. [ECR-3317]

---

exonum-java-binding/core/rust/exonum-java/exonum-java

Now script will correctly resolve EXONUM_HOME hence it will be possible to run it via symlink.
The code is taken from Maven executable script and slightly modified.
---
See: https://jira.bf.local/browse/ECR-3368

Fix bin/exonum-java script [ECR-3368]

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/OpenIndexRegistry.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/View.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/AbstractIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/AbstractListIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/EntryIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/IndexAddress.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/KeySetIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ListIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/MapIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofListIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/StorageIndex.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/StoragePreconditions.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxy.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/OpenIndexRegistryTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/AbstractIndexProxyTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseIndexProxyTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/EntryIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/IndexAddressTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/KeySetIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ListIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/MapIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofListIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxyIntegrationTest.java

De-duplicate Exonum indexes to overcome the MerkleDB Fork limitation.
---
See: https://jira.bf.local/browse/ECR-3359

De-duplicate indexes [ECR-3359]

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/KeySetIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/MapIndex.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/MapIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxy.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/KeySetIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/MapIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxyIntegrationTest.java

Add size() and isEmpty() methods to KeySetIndex, ValueSetIndex, MapIndex and ProofMapIndex.
---
See: https://jira.bf.local/browse/ECR-3316

Add size() and isEmpty() methods to indices [ECR-3316]

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Fork.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/ModificationCounter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Snapshot.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/View.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/AbstractIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ConfigurableRustIter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ImmutableModificationCounter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/IncrementalModificationCounter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/KeySetIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ListIndex.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ListSpliterator.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/MapIndex.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ModificationCounter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/StorageIterators.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxy.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/SnapshotTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/AbstractIndexProxyTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseListIndexIntegrationTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ConfigurableRustIterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ImmutableModificationCounterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/IncrementalModificationCounterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ListSpliteratorTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/MapIndexProxyIntegrationTest.java

Allow to iterate over one index and modify any other independent
index as this is determined to be safe with MerkleDB.
Modification of the index during iteration over it (even if it
happens through separate proxies) is still prohibited and must
be reliably detected. As indexes are de-duplicated now (#1039), no extra
effort is required to ensure such reliable detection (except the tests).
---
See: 
- https://jira.bf.local/browse/ECR-3322
- https://jira.bf.local/browse/ECR-3359 (de-duplication)

Relax index modification restrictions [ECR-3322]:

---

.travis.yml
exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/build.rs
exonum-java-binding/core/rust/integration_tests/tests/node_context.rs
exonum-java-binding/core/rust/src/lib.rs
exonum-java-binding/package_app.sh

Fixes static linkage on Mac and reenables Travis CI.
---
See: https://jira.bf.local/browse/ECR-3382

Fix Mac OS build [ECR-3382]

---

exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/MapIndexProxyGroupIntegrationTest.java

It seems the collection groups became independent in MerkleDB,
and modifications of a collection in one group cannot affect
collections in other groups, even if first group id is a sub-prefix
of the other group id.
---

Enable a test verifying independence of collection groups

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java

Use the numeric service id for better efficiency.
**The patch is in the last commit 7c5abea**
---
See: https://jira.bf.local/browse/ECR-3435

Use numeric service id in ServiceRuntime operations [ECR-3435]

---

exonum-java-binding/core/checkstyle-suppressions.xml
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceWrapper.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceWrapperTest.java

Add an operation to register APIs of newly instantiated services.
Removing is not supported till it is needed.
**Commits to review: ed52c93**
---
See: https://jira.bf.local/browse/ECR-3434

Register the service API [ECR-3434]

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/transport/VertxServer.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/transport/VertxServerIntegrationTest.java

Use a larger timeout of 5 seconds, and run these tests sequentially
as each of them creates its own thread pool increasing contention
for CPU.
As the server starts *asynchronously* the actual port is accessible
only after that operation completes (not immediately). The previous
implementation almost always logged 0 when 0 was requested.
---

Fix the flaky tests

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/integration_tests/Cargo.toml

This reverts commit ee450f5f
---
See: https://jira.bf.local/browse/ECR-3492

Revert updating lazy_static [ECR-3492]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/KeySetIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxy.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/KeySetIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxyIntegrationTest.java

A simple non-splittable implementation is OK for the sets are not
currently sized.
---

Add #stream to sets:

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/exonum-java/Cargo.toml
exonum-java-binding/core/rust/exonum-java/src/main.rs
exonum-java-binding/core/rust/exonum-java/src/node_builder.rs
exonum-java-binding/core/rust/integration_tests/Cargo.toml

Pointing branch to latest exonum 0.12. BTC anchoring service is disabled because it breaks the dynamic binding on the app start.
---
See: https://jira.bf.local/browse/ECR-3450

Update to exonum 0.12 [ECR-3450]

---

exonum-java-binding/CHANGELOG.md

Update Changelog for the 0.8.0 release

---

exonum-java-binding/common/pom.xml

Update lazysodium and add jcenter repository for it's dependencies.
See: https://github.com/terl/lazysodium-java/issues/55
---

Update lazysodium and add jcenter repository

---

exonum-java-binding/common/pom.xml

Revert lazysodium to 4.0.1 until https://github.com/terl/lazysodium-java/issues/56 is fixed as per request from @dip56 .
---

Revert lazysodium to 4.0.1

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Fork.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/OpenIndexRegistry.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Snapshot.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/View.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/ForkIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/OpenIndexRegistryTest.java

Implement Fork#checkpoint and Fork#rollback required for proper
ServiceRuntime#beforeCommit implementation in Java.
Make Forks use temporary cleaners to be able to destroy all the objects
created before checkpoint or rollback. These operations are for
framework only, and users receiving the fork in a method can still rely
on the fork being accessible for the duration of the method operation
(i.e., no checkpoint/rollback will occur whilst Fork is used
by the client).
---
See: https://jira.bf.local/browse/ECR-3520

Implement Fork#rollback [ECR-3520]:

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceConfiguration.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceWrapper.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Configuration.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Service.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceConfigurationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
exonum-java-binding/fakes/src/main/java/com/exonum/binding/fakes/services/service/TestService.java
exonum-java-binding/fakes/src/test/java/com/exonum/binding/fakes/services/service/TestServiceIntegrationTest.java
exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/TestService.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestService.java

Update the ServiceRuntime to the newer Runtime specification from the core (as of https://github.com/exonum/exonum/commit/fd3b037c2b71bd1253c0b867687e7510d1e2acb9).
---
**See: https://jira.bf.local/browse/ECR-3588**

Update service runtime [ECR-3588]

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceWrapper.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Service.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Fork.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/ForkIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/NativeResourceManagerIntegrationTest.java

Add `ServiceRuntime#beforeCommit`.
---
See: https://jira.bf.local/browse/ECR-3584

Add ServiceRuntime#beforeCommit [ECR-3584]

---

exonum-java-binding/pom.xml
exonum-light-client/CHANGELOG.md
exonum-light-client/README.md
exonum-light-client/generate-javadocs.sh
exonum-light-client/pom.xml

Prepare Java Light Client v0.4.0 release. Also, fix Javadoc generation with JDK 13+.
---
See: https://wiki.bf.local/display/EJB/Java+Light+Client+0.4.0+Release+Checklist

Prepare Java Light Client v0.4.0 release

---

exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/CheckedProof.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/CheckedListProof.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/CheckedListProofImpl.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/FlatListProof.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/InvalidProofException.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/ListProofElementEntry.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/ListProofEntry.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/ListProofHashedEntry.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/UncheckedListProofAdapter.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/list/FlatListProofTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/list/ListProofHashCalculatorTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/list/ListProofUtils.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofListContainsMatcher.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofListIndexProxyIntegrationTest.java

Add flat list proof support.
---
---
See: 
* https://jira.bf.local/browse/ECR-3608
* https://wiki.bf.local/display/EXN/Flat+list+proofs

Add flat list proof support [ECR-3608]

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/RuntimeModule.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeConfigurationIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/TestServiceModule.java

Add a missing binding for ServicesFactory in the runtime module.
Add an integration test for the runtime configuration.
---

Fix the runtime module:

---

exonum-java-binding/common/pom.xml
exonum-java-binding/core/pom.xml
exonum-java-binding/cryptocurrency-demo/pom.xml
exonum-java-binding/pom.xml
exonum-java-binding/qa-service/pom.xml
exonum-java-binding/testkit/pom.xml
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitAuditorParameterizationTest.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitExtensionTest.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitParameterizationTest.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTestWithArtifactsCreated.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestService.java
exonum-java-binding/testkit/src/test/proto/TestMessages.proto

Add configuration usage in TestService initialization and corresponding tests.
---
See: https://jira.bf.local/browse/ECR-3652

Add configuration usage in TestService initialization [ECR-3652]

---

exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/CoreSchemaProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseIndexProxyTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseListIndexIntegrationTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseListIndexProxyGroupTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxyIntegrationTest.java

The remaining disabled tests are:
- CoreSchema: its compilation is disabled in Rust, must be fixed
in ECR-3722; actual config — updated in ECR-3612
- ProofList: the proofs are flat in the core, but not yet in our code:
ECR-3673 and ECR-3614
---

Re-enable the tests that aren't broken [ECR-3709]:

---

exonum-java-binding/generate-javadocs.sh

It is skipped on the previous step; and need not to be done on this one.
[ci skip]
---

Skip building the Rust lib when javadoc is generated:

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/build.rs
exonum-java-binding/core/rust/src/lib.rs
exonum-java-binding/core/rust/src/proxy/runtime.rs
exonum-java-binding/core/rust/src/utils/jni_cache.rs

Updated to revision 47114e3 as no functional changes were made since 0f44d1c
---
See: https://jira.bf.local/browse/ECR-3698

Update ServiceRuntime proxy in Rust to the current Exonum revision [ECR-3698]

---

exonum-java-binding/common/src/main/java/com/exonum/binding/common/blockchain/TransactionResult.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/message/TransactionMessage.java
exonum-java-binding/common/src/main/proto/blockchain.proto
exonum-java-binding/common/src/main/proto/common.proto
exonum-java-binding/common/src/main/proto/consensus.proto
exonum-java-binding/common/src/main/proto/runtime.proto
exonum-java-binding/common/src/main/proto/types.proto
exonum-java-binding/common/src/test/java/com/exonum/binding/common/message/ParsedTransactionMessageTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/message/SignedMessageTest.java
exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/build.rs
exonum-java-binding/core/rust/src/proxy/runtime.rs
exonum-java-binding/core/rust/src/utils/jni_cache.rs
exonum-java-binding/core/src/main/java/com/exonum/binding/core/proxy/Cleaner.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/Pf4jServiceLoader.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceLoader.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/main/proto/blockchain.proto
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/Pf4jServiceLoaderIntegrationTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeConfigurationIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
exonum-java-binding/fakes/src/main/java/com/exonum/binding/fakes/NativeFacade.java
exonum-java-binding/fakes/src/test/java/com/exonum/binding/fakes/services/ServiceArtifactsIntegrationTest.java

Brings together native and Java (reviewed separately), updated to newer core: exonum/exonum@47114e3
---
See the indy commits.

Upgrade to newer core revision

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/JavaArtifactNames.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/Pf4jServiceLoader.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/RuntimeId.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceArtifactId.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/GuiceServicesFactoryTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/JavaArtifactNamesTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/Pf4jServiceLoaderIntegrationTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceArtifactIdTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeConfigurationIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceWrapperTest.java
exonum-java-binding/fakes/src/main/java/com/exonum/binding/fakes/services/ServiceArtifacts.java
exonum-java-binding/fakes/src/test/java/com/exonum/binding/fakes/services/ServiceArtifactsIntegrationTest.java

Clarified the usage of artifact name in the native API;
also made ServiceArtifactId compatible with any valid
artifact id.
Verification of correct Java artifact id are pushed to the loader.
Also a RuntimeId enum is added with well-known service runtime ids.
---
See: **https://jira.bf.local/browse/ECR-3733**

Use artifact name in native API: [ECR-3733]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/InvalidProofException.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/ProofHashes.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/FlatListProof.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/map/MapProofStatus.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/map/UncheckedFlatMapProof.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/ProofHashesTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/list/FlatListProofTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/map/UncheckedFlatMapProofTest.java
exonum-java-binding/core/findbugs-exclude.xml

Check that all hashes are SHA-256 hashes (32-byte long).
---
See: https://jira.bf.local/browse/ECR-3687

Check the hash size during proof verification [ECR-3687]

---

exonum-java-binding/core/pom.xml
exonum-java-binding/core/spotbugs-exclude.xml
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/main/proto/deploy_arguments.proto
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java

Extract DeployArguments in a separate file as it might be
subsequently used as a public message to construct the deploy
transaction.
The messages remaining in 'service_runtime.proto' are for internal
usage (i.e., interaction between Java Runtime and the Rust proxy).
---
See: https://jira.bf.local/browse/ECR-3721

Extract DeployArguments to a separate proto file: [ECR-3721]

---

.travis.yml

Resolves the build failure which started to occur when 6.1.2 had been
updated on Homebrew to 6.3.6: ECR-3772.
---
See: https://jira.bf.local/browse/ECR-3772

Disable Mac builds

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/src/lib.rs
exonum-java-binding/core/rust/src/proxy/runtime.rs

- Updated to the revision `7404bac` of exonum.
- Switched to the `protobuf_convert` macro.
---
See: https://jira.bf.local/browse/ECR-3778

Update EJB to the newer revision of exonum [ECR-3778]

---

.travis.yml
exonum-java-binding/core/rust/build.rs

To avoid compilation error on Mac with recent Homebrew rocksdb package
---
See: https://jira.bf.local/browse/ECR-3772

Link zstd statically with the library [ECR-3772]

---

exonum-java-binding/common/src/main/java/com/exonum/binding/common/message/SignedMessage.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/message/SignedMessageTest.java

Now hash(SignedMessage) == hash(protobuf representation)
---

Fix SignedMessage hashing

---

exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java

Enable TestKit tests that depend on transaction results update (#1174).

Enabled some TestKit tests

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/DispatcherSchema.java

In used core revision and in current master it's MapIndex, not ProofMapIndex https://github.com/exonum/exonum/blob/6d7cc3a9c6d10dc762fe5b849d3facde35bc2c21/exonum/src/runtime/dispatcher/schema.rs#L58
---

Fix DispatcherSchema#serviceInstances return type

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofListIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxy.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseProofMapIndexProxyIntegrationTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/DisabledProofTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofListIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxyNoKeyHashingIntegrationTest.java

The proof methods are temporarily deprecated till ECR-3666/ECR-2545.
All proof tests are disabled.
The tests of ProofList are re-enabled.
---
See: https://jira.bf.local/browse/ECR-3786

Deprecate proof methods to prevent their usage [ECR-3786]:

---

exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/TimeSchemaProxyIntegrationTest.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java

Enable time service tests that are dependent on hashing ProofMap.

Enable time service tests

---

exonum-java-binding/core/src/test/resources/log4j2-test.xml
exonum-java-binding/qa-service/src/test/resources/log4j2-test.xml

No tests use that (they were removed when they were parallelized),
it just uses memory.
---
See: https://jira.bf.local/browse/ECR-3704

Remove the ListAppender from the log configuration [ECR-3704]:

---

CONTRIBUTING.md
exonum-java-binding/package_app.sh

Use static linkage on both Linux and Mac, using the updated rocksdb library from Exonum Ubuntu PPA.
---
See: https://jira.bf.local/browse/ECR-3852

Use static linkage on Linux [ECR-3852]

---

exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseProofMapIndexProxyIntegrationTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxyGroupNoKeyHashingIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxyNoKeyHashingIntegrationTest.java

Move tests of iterators to the base test to ensure they work
for both ProofMap variants.
---
See: https://jira.bf.local/browse/ECR-3871

Test iterators for both ProofMap variants [ECR-3871]:

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/src/storage/proof_list_index.rs
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/AbstractListIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ListIndex.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ListIndexProxy.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofListIndexProxy.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseListIndexIntegrationTestable.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ListIndexProxyIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofListIndexProxyIntegrationTest.java

Extract these operations to the interface. Move their tests
to the base test of interface operations, make some of them
parameterized.
---
See: https://jira.bf.local/browse/ECR-3669

Add truncate and pop to ProofListIndexProxy [ECR-3669]

---

exonum-java-binding/core/rust/Cargo.lock

^ bincode v1.2.0 -> v1.2.1
^ bindgen v0.49.2 -> v0.49.4
^ http v0.1.19 -> v0.1.21
^ libc v0.2.65 -> v0.2.66
^ lock_api v0.3.1 -> v0.3.2
^ mio v0.6.19 -> v0.6.21
^ num-traits v0.2.9 -> v0.2.10
^ openssl v0.10.25 -> v0.10.26
^ openssl-sys v0.9.52 -> v0.9.53
^ protobuf-convert v0.2.0 -> v0.2.1
^ rpassword v4.0.1 -> v4.0.3
^ security-framework v0.3.3 -> v0.3.4
^ serde_json v1.0.42 -> v1.0.44
^ signal-hook v0.1.11 -> v0.1.12
^ signal-hook-registry v1.1.1 -> v1.2.0
^ snow v0.6.1 -> v0.6.2
^ subtle v2.2.1 -> v2.2.2
^ syn v1.0.8 -> v1.0.11
^ tokio-executor v0.1.8 -> v0.1.9
^ tokio-reactor v0.1.10 -> v0.1.11
^ tokio-threadpool v0.1.16 -> v0.1.17
^ tokio-timer v0.2.11 -> v0.2.12
^ unicode-normalization v0.1.9 -> v0.1.11
^ unicode-width v0.1.6 -> v0.1.7
^ vcpkg v0.2.7 -> v0.2.8
---
See: …

Update locked Rust dependencies:

---

CONTRIBUTING.md

Make it point to the landing page,
which always has the link to the most recent JDK.
[skip ci]
---

Fix the JDK link:

---

exonum-java-binding/core/rust/integration_tests/tests/jni_cache_not_initialized.rs
exonum-java-binding/core/rust/src/handle/resource_manager/imp.rs
exonum-java-binding/core/rust/src/utils/mod.rs

`assert_panics()` should be used instead of `#[should_panic(expected = "Expected message")]` in tests in case there is more than one way of panicking with the expected message.
---
See: https://jira.bf.local/browse/ECR-3353

Make `assert_panics()` a library function [ECR-3353].

---

exonum-java-binding/exonum_launcher_java_plugins/README.md
exonum-java-binding/exonum_launcher_java_plugins/setup.py

Python modules have been published with the following changes.
---
See: https://jira.bf.local/browse/ECR-3992

Update README.md and setup.py for Python modules [ECR-3992]

---

exonum-java-binding/core/rust/src/storage/mod.rs
exonum-java-binding/core/rust/src/storage/proof_list_index.rs
exonum-java-binding/core/rust/src/storage/proof_map_index_next.rs
exonum-java-binding/core/rust/src/storage/raw_proof_map_index.rs
exonum-java-binding/core/rust/src/utils/conversion.rs
exonum-java-binding/core/rust/src/utils/mod.rs

Hashing and non-hashing ProofMap have different JNI implementations since now.
---
See: https://jira.bf.local/browse/ECR-3983

Separate JNI implementation for ProofMap [ECR-3983]

---

exonum-java-binding/core/rust/generate_licenses.sh
exonum-java-binding/package_app.sh

Cargo-licesense 0.3.0 offers a pretty `--json` option which solves our formatting issues.
Also fixes output directory and now native licenses file is correctly packaged. (Why haven't we checked it before?)
---
See: https://jira.bf.local/browse/ECR-4001
See: https://jira.bf.local/browse/ECR-3968

Fix licenses generation [ECR-4001] [ECR-3968]

---

checkstyle.xml
exonum-java-binding/common/checkstyle-suppressions.xml
exonum-java-binding/core/checkstyle-suppressions.xml
exonum-java-binding/cryptocurrency-demo/checkstyle-suppressions.xml
exonum-java-binding/integration-tests/checkstyle-suppressions.xml
exonum-java-binding/qa-service/checkstyle-suppressions.xml
exonum-light-client/checkstyle-suppressions.xml

Fixed broken links to Checkstyle DTDs.
See also the source of DTDs on the Github:
https://github.com/checkstyle/checkstyle/tree/master/src/main/resources/com/puppycrawl/tools/checkstyle

Fix links to Checkstyle DTDs

---

exonum-java-binding/app/pom.xml
exonum-java-binding/benchmarks/pom.xml
exonum-java-binding/bom/pom.xml
exonum-java-binding/common/pom.xml
exonum-java-binding/core/pom.xml
exonum-java-binding/cryptocurrency-demo/pom.xml
exonum-java-binding/fake-service/pom.xml
exonum-java-binding/fakes/pom.xml
exonum-java-binding/integration-tests/pom.xml
exonum-java-binding/packaging/pom.xml
exonum-java-binding/pom.xml
exonum-java-binding/qa-service/pom.xml
exonum-java-binding/service-archetype/pom.xml
exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
exonum-java-binding/testing/pom.xml
exonum-java-binding/testkit/pom.xml
exonum-java-binding/time-oracle/pom.xml
exonum-light-client/pom.xml
pom.xml

The other things are namespace declarations
and are not retrievable resources, hence _must_ remain intact.
Also, remove tidy-maven-plugin: it forbids HTTPS in schema location, required
by the Maven POM Convention.
See also:
- ECR-4051
- ECR-4052
---

Use HTTPS for Maven POM Schema

---

exonum-java-binding/core/rust/src/storage/entry.rs
exonum-java-binding/core/rust/src/storage/mod.rs

I'm starting to hate these copy-pasted methods....
To reviewers: it's a copy of proof_entry module, without `nativeGetHash` method.
---
See: https://jira.bf.local/browse/ECR-3979

Add EntryIndex native methods [ECR-3979]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/rust/integration_tests/tests/jni_cache.rs
exonum-java-binding/core/rust/src/proxy/runtime.rs
exonum-java-binding/core/rust/src/utils/jni_cache.rs
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceWrapper.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Service.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java

The name has changed in the core. _before_ transactions handler
will be added later in: ECR-4016
---
See: 
* https://jira.bf.local/browse/ECR-4057
* ECR-4016
* ECR-4058

Rename Service#beforeCommit into afterTransactions [ECR-4057]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/checkstyle-suppressions.xml
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/TransactionInvoker.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/UnexpectedTransactionExecutionException.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/transaction/Transaction.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/TransactionInvokerTest.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaService.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/CreateCounterTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ErrorTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ThrowingTxTest.java

Make any exceptions but TransactionExecutionException be communicated
as 'unexpected' (wrapped into UnexpectedTransactionExecutionException),
but _only_ thrown from the transaction method, not from any surrounding
code (e.g., ServiceRuntime, ServiceWrapper, etc.)
Native code needs to be updated separately: ECR-4054
Also, update the Transaction documentation.
---
See: https://jira.bf.local/browse/ECR-3988

Clarify exception handling in Transaction methods [ECR-3988]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/common/src/main/java/com/exonum/binding/common/blockchain/ExecutionStatuses.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/blockchain/ExecutionStatusesTest.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/Block.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/Blockchain.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/CoreSchema.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/transaction/TransactionExecutionException.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/CoreSchemaIntegrationTest.java
exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/CreateWalletTxIntegrationTest.java
exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/TransferTxIntegrationTest.java
exonum-java-binding/fake-service/src/main/java/com/exonum/binding/fakeservice/FakeService.java
exonum-java-binding/fake-service/src/main/proto/transactions.proto
exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/BlockchainIntegrationTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/CreateCounterTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ErrorTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/IncrementCounterTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ThrowingTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/TransactionMessages.java
exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java

Add `Blockchain#getCallErrors` and update `getTxResult` to work with the new blockchain schema in the core. The core now aggregates the call errors by blocks.
---
- Shall we add static factory methods for `CallInBlock` (highly unclear API): https://jira.bf.local/browse/ECR-4070?
- Shall we add extra overloads for getTxResult (eg. by location): https://jira.bf.local/browse/ECR-4014?focusedCommentId=71301&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-71301
- Matchers for errors: https://jira.bf.local/browse/ECR-4067 
---
See: https://jira.bf.local/browse/ECR-4014

Support call errors aggregation in blocks [ECR-4014]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/common/src/main/java/com/exonum/binding/common/blockchain/CallInBlocks.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/blockchain/TransactionLocation.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/blockchain/CallInBlocksTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/serialization/TransactionLocationSerializerTest.java

---
See: https://jira.bf.local/browse/ECR-4083

ECR-4083: long to int migration

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/exonum-java/src/node.rs
exonum-java-binding/core/rust/src/cmd/mod.rs
exonum-java-binding/core/rust/src/cmd/run_dev.rs
exonum-java-binding/core/rust/src/lib.rs
exonum-java-binding/core/rust/src/proxy/runtime.rs
exonum-java-binding/core/rust/src/storage/key_set_index.rs
exonum-java-binding/core/rust/src/storage/list_index.rs
exonum-java-binding/core/rust/src/storage/map_index.rs
exonum-java-binding/core/rust/src/storage/proof_list_index.rs
exonum-java-binding/core/rust/src/storage/proof_map_index.rs
exonum-java-binding/core/rust/src/storage/proof_map_index_next.rs
exonum-java-binding/core/rust/src/storage/raw_proof_map_index.rs
exonum-java-binding/core/rust/src/storage/value_set_index.rs
exonum-java-binding/core/rust/src/testkit/mod.rs
exonum-java-binding/core/rust/src/utils/jni_cache.rs

- Multiple fixes for the latest Core API
- ArtifactId passed in protobuf-serialized format
- Removed check for ArtifactId.runtime_id == JAVA_RUNTIME_ID. It seems to be purely Core's responsibility
- Multiple fixes for the latest `clippy`.
---
See: https://jira.bf.local/browse/ECR-4097

Update native to revision b81d64ef of Core [ECR-4097]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/rust/exonum-java/src/node.rs

Support different supervisor modes in exonum-java

---

exonum-java-binding/core/rust/src/cmd/mod.rs

Current output of `exonum-java --help`:
```
java_bindings 0.10.0-SNAPSHOT
Exonum Team <contact@exonum.com>
Exonum Java Bindings Application.
Configures and runs Exonum node with Java runtime enabled.
See https://exonum.com/doc/version/0.13-rc.2/get-started/java-binding/#node-configuration
USAGE:
exonum-java <SUBCOMMAND>
FLAGS:
-h, --help       
Prints help information
-V, --version    
Prints version information
SUBCOMMANDS:
finalize             Generate final node configuration using public configs of other nodes in the network
generate-config      Generate public and private configs of the node
generate-template    Generate common part of the nodes configuration
help                 Prints this message or the help of the given subcommand(s)
maintenance          Perform different …
```

Add documentation link for exonum-java [ECR-3090]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/MultiplexingNodeDecorator.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceWrapper.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Service.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceWrapperTest.java

---
See: https://jira.bf.local/browse/ECR-4133

[ECR-4133] Add service resume

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/AbstractAccess.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/OpenIndexRegistry.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/OpenIndexRegistryTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseIndexProxyTestable.java

Modified the AbstractAccess to resolve
addresses into numeric ids and then use the ids
to cache indexes. That is required for correct
operation of Prefixed accesses and will be
fully tested when they are added.
This patch requires the native code for operation,
and currently does not pass tests.
---
See: https://jira.bf.local/browse/ECR-4156

Cache indexes by numeric ids [ECR-4156]:

---

exonum-java-binding/common/src/main/java/com/exonum/binding/common/message/ParsedTransactionMessage.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/message/SignedMessage.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/message/TransactionMessage.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/message/ParsedTransactionMessageTest.java
exonum-java-binding/common/src/test/java/com/exonum/binding/common/message/SignedMessageTest.java
exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/exonum-java/Cargo.toml
exonum-java-binding/core/rust/exonum-java/src/main.rs
exonum-java-binding/core/rust/exonum-java/src/node.rs
exonum-java-binding/core/rust/integration_tests/tests/node_context.rs
exonum-java-binding/core/rust/src/proxy/runtime.rs
exonum-java-binding/core/rust/src/runtime/error.rs
exonum-java-binding/core/rust/src/storage/blockchain.rs
exonum-java-binding/core/rust/src/storage/proof_list_index.rs
exonum-java-binding/core/rust/src/storage/proof_map_index_next.rs
exonum-java-binding/core/rust/src/storage/raw_proof_map_index.rs
exonum-java-binding/core/rust/src/utils/conversion.rs
exonum-java-binding/core/rust/src/utils/jni_cache.rs
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/BlockchainIntegrationTest.java

This update brings resuming services and Access types without lifetime restrictions. Based on custom Exonum Core branch.
---
See: https://jira.bf.local/browse/ECR-4130

Update to revision c46b533 of Core [ECR-4130]

---

exonum-java-binding/core/pom.xml
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/ForkTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/SnapshotTest.java
exonum-java-binding/pom.xml

Powermock is not likely to support JUnit 5 soon.
Similar tests could be implemented either by abstracting
the native API or via the native resource manager (if
its operations are made available to Java code).
---
See: https://jira.bf.local/browse/ECR-1614

Remove the disabled Powermock-based tests: [ECR-1614]

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/src/storage/blockchain_data.rs
exonum-java-binding/core/rust/src/storage/mod.rs
exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/BlockchainDataIntegrationTest.java
exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/BlockchainDataIntegrationTest.java

nativeCanModify is __not__ implemented,
nativeGetServiceName is implemented
---
See: https://jira.bf.local/browse/ECR-4169

Add BlockchainData native methods [ECR-4169]

---

exonum-java-binding/CHANGELOG.md
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/Blockchain.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/BlockchainData.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/BlockchainProofs.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/BlockchainDataIntegrationTest.java
exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/BlockchainDataIntegrationTest.java

Add BlockchainData#createIndexProof.
---
See: https://jira.bf.local/browse/ECR-4176

Add BlockchainData#createIndexProof [ECR-4176]

---

exonum-java-binding/core/rust/Cargo.lock
exonum-java-binding/core/rust/Cargo.toml
exonum-java-binding/core/rust/exonum-java/src/node.rs
exonum-java-binding/core/rust/integration_tests/tests/node_context.rs
exonum-java-binding/core/rust/src/lib.rs
exonum-java-binding/core/rust/src/proxy/node.rs
exonum-java-binding/core/rust/src/proxy/runtime.rs
exonum-java-binding/core/rust/src/storage/access.rs
exonum-java-binding/core/rust/src/storage/blockchain_data.rs
exonum-java-binding/core/rust/src/storage/key_set_index.rs
exonum-java-binding/core/rust/src/storage/list_index.rs
exonum-java-binding/core/rust/src/storage/map_index.rs
exonum-java-binding/core/rust/src/storage/proof_list_index.rs
exonum-java-binding/core/rust/src/storage/proof_map_index.rs
exonum-java-binding/core/rust/src/storage/proof_map_index_next.rs
exonum-java-binding/core/rust/src/storage/raw_proof_map_index.rs
exonum-java-binding/core/rust/src/storage/readonly_erased_access.rs
exonum-java-binding/core/rust/src/storage/value_set_index.rs
exonum-java-binding/core/rust/src/testkit/mod.rs
exonum-java-binding/core/rust/src/testkit/time_provider.rs
exonum-java-binding/core/rust/src/utils/errors.rs
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/serialization/BlockSerializer.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/NodeProxy.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/BlockchainDataIntegrationTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/serialization/BlockSerializerTest.java
exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceNodeProxyIntegrationTest.java

This PR updates native to the most recent (almost) Exonum revision.
Attention: The native code updates are aimed at reduction of diff size, not on proper implementation. The most important consequence is that imports of iterator types in `storage` module are not optimal and must be rewritten (ECR-TBD). Also see individual review comments.
TestKit tests are __not__ working.
Integration tests module is __not__ tested.
---
See: https://jira.bf.local/browse/ECR-4201

Update to recent Exonum revision [ECR-4201]

---

exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/ApiController.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaSchema.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaService.java
exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java
exonum-java-binding/qa-service/src/main/proto/transactions.proto
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ApiControllerTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/CreateCounterTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ErrorTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/IncrementCounterTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/ThrowingTxTest.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/TransactionMessages.java
exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/TransactionUtils.java

Qa service schema had to use a separate map for names as
proof maps didn't use to allow string keys.
With hashing proof map there is no longer a need for a separate
collection for names.
The remaining usage: CryptocurrencySchema#wallets — uses
verified Public Keys.
--- 
System tests: https://git.xdev.re/exonum-qa/autotests-exonum-java-binding/merge_requests/12
---
See: https://jira.bf.local/browse/ECR-3849

Replace raw proof map in QA service with hashing one [ECR-3849]:

---

.travis.yml

- sudo is no-op;
- matrix is a jobs alias.
---

Fix some Travis warnings:

---

exonum-java-binding/CHANGELOG.md

Fix a missing backtick in changelog
---

Fix typo in changelog

---

exonum-java-binding/core/rust/src/utils/jni_cache.rs

---
See: https://jira.bf.local/browse/ECR-4198

Check JNI cache entries validity immediately on creation [ECR-4198]

---

.travis.yml
exonum-java-binding/exonum_launcher_java_plugins/.gitignore

- Ignore folder with generated sources
- Improve Travis cache operation:
- Cache `~/.rustup` and remove the `~/.cargo/registry/src`
as recommended in Travis Rust docs:
https://docs.travis-ci.com/user/languages/rust/#dependency-management
- Remove messages from the Travis cache
---

Various fixes

---

.travis.yml

https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296
---

Fix Mac builds on Travis

---

exonum-java-binding/pom.xml
exonum-java-binding/service-archetype/pom.xml
exonum-java-binding/service-archetype/src/main/resources-filtered/archetype-resources/pom.xml

Make the archetype pom a [filtered resource](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html) (TIL), so that versions
of dependencies can be substituted from the build properties.
We will no longer have to update them manually 🎉 
The downside is that remaining property references must be escaped.
---
A similar approach is used in the collection of Apache Maven archetypes, though,
with a properties _file_: 
- https://github.com/apache/maven-archetypes/blob/maven-archetype-bundles-1.4/pom.xml#L94
- https://github.com/apache/maven-archetypes/blob/maven-archetype-bundles-1.4/plugin-versions.properties

Prototype properties expansion (aka resource filtering):

---

exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/Block.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/Blockchain.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/CallRecords.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/CoreSchema.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/ExecutionException.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Service.java
exonum-java-binding/core/src/main/java/com/exonum/binding/core/transaction/Transaction.java
exonum-java-binding/fake-service/src/main/java/com/exonum/binding/fakeservice/FakeService.java
exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/BlockchainIntegrationTest.java
exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/ServiceRuntimeIntegrationTest.java
exonum-java-binding/site-examples/src/test/java/com/exonum/binding/example/testing/TestkitExamplesTest.java

Add CallRecords providing access to the execution error
as a single object; and creating proofs of their correctness.
2ab7fe8 — to review
---
See: https://jira.bf.local/browse/ECR-4344

Add CallRecords [ECR-4344]

---

exonum-java-binding/common/src/main/java/com/exonum/binding/common/crypto/CryptoFunctions.java
exonum-java-binding/common/src/main/java/com/exonum/binding/common/crypto/Ed25519CryptoFunction.java

The Ed25519CryptoFunction used to initialize an instance of
itself in a static initializer, making it impossible to
instantiate it with a different library loading mode (as
the library can only be loaded once into a JVM process).
This PR moves the instance initialization to CryptoFunctions,
where it happens lazily (just as previously) in a holder class.
---

Fix the test of Ed25519 operation with the system sodium:

---

.travis.yml
exonum-java-binding/CHANGELOG.md
exonum-java-binding/common/pom.xml
exonum-java-binding/common/src/main/java/com/exonum/binding/common/serialization/ProtobufReflectiveSerializer.java

On Mac with Java 14, JNA appears to not search
in /usr/local/lib, where sodium is installed.
See https://github.com/java-native-access/jna/issues/1175

Add Java 14 support
