- exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/ApiController.java
Add text/plain content-type to string replies.
---
See: https://jira.bf.local/browse/ECR-1703
> ECR-1703 Add text/plain content-type to string replies

- exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTx.java
- exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTxTest.java
Add the context of the error condition.
> Improve the error message:

- .github/PULL_REQUEST_TEMPLATE.md
Add links to appropriate sections of the contribution guide to the PR template.
> Add appropriate links to PR template.

- exonum-java-binding-core/rust/ejb-app/Cargo.toml
- exonum-java-binding-core/rust/ejb-app/src/main.rs
Configuration service bundled into EJB App (without possibility to disable it).
---
See: https://jira.bf.local/browse/ECR-1323
> Bundle exonum-configuration service into EJB App [ECR-1323] 

- exonum-java-proofs/pom.xml
- exonum-java-proofs/src/main/java/com/exonum/binding/hash/AbstractNonStreamingHashFunction.java
- exonum-java-proofs/src/main/java/com/exonum/binding/hash/AbstractStreamingHasher.java
- exonum-java-proofs/src/test/java/com/exonum/binding/hash/AbstractByteHasherTest.java
- exonum-java-proofs/src/test/java/com/exonum/binding/hash/AbstractNonStreamingHashFunctionTest.java
- exonum-java-proofs/src/test/java/com/exonum/binding/hash/AbstractStreamingHasherTest.java
- exonum-java-proofs/src/test/java/com/exonum/binding/hash/FunnelsTest.java
- exonum-java-proofs/src/test/java/com/exonum/binding/hash/HashCodeTest.java
- exonum-java-proofs/src/test/java/com/exonum/binding/hash/HashTestUtils.java
- exonum-java-proofs/src/test/java/com/exonum/binding/hash/HashingTest.java
- exonum-java-proofs/src/test/java/com/exonum/binding/hash/MessageDigestHashFunctionTest.java
- exonum-java-proofs/src/test/java/com/exonum/binding/test/EqualsTester.java
- exonum-java-proofs/src/test/java/com/exonum/binding/test/RelationshipTester.java
- pom.xml
Imported Guava tests with almost no changes.
---
See: https://jira.bf.local/browse/ECR-1367
> ECR-1367 Import Guava tests

- exonum-java-binding-core/rust/ejb-app/start_cryptocurrency_node.sh
Update the script to start a cryptocurrency service to work on Mac.
> update script for creating cryptocurrency node

- exonum-java-binding-core/src/main/java/com/exonum/binding/messages/BinaryMessage.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/messages/Message.java
- exonum-java-binding-core/src/test/java/com/exonum/binding/messages/BinaryMessageTest.java
- exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/CryptocurrencyServiceImpl.java
- exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTx.java
- exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/TransferTx.java
- exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTxTest.java
- exonum-java-binding-cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxTest.java
Verify signatures of transaction messages.
---
See: https://jira.bf.local/browse/ECR-1755
> Verify signatures of transaction messages [ECR-1755].

- exonum-java-proofs/src/test/java/com/exonum/binding/storage/serialization/StandardSerializersRoundtripTest.java
Add StandardSerializers roundtrip test.
---
See: https://jira.bf.local/browse/ECR-889
> ECR-889 Add StandardSerializers roundtrip test

- .travis.yml
- exonum-java-binding-bom/pom.xml
- exonum-java-binding-core/pom.xml
- exonum-java-binding-core/rust/Cargo.toml
- exonum-java-binding-core/rust/ejb-app/Cargo.toml
- exonum-java-binding-core/rust/integration_tests/Cargo.toml
- exonum-java-binding-cryptocurrency-demo/pom.xml
- exonum-java-binding-fakes/pom.xml
- exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/services/service/TestService.java
- exonum-java-binding-qa-service/pom.xml
- exonum-java-binding-service-archetype/pom.xml
- exonum-java-binding-service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-proofs/pom.xml
- exonum-java-testing/pom.xml
- pom.xml
Release v0.2.
PLEASE DON'T MERGE YET.
> Release v0.2

- README.md
If you are using Exonum in your project and want to be listed on our website & GitHub list — write us a line to <exonum@bitfury.com>.
(https://github.com/exonum/exonum/pull/849)
> Update readme with "contact us" information

- exonum-java-binding-core/src/main/java/com/exonum/binding/storage/database/MemoryDb.java
* Add link to NodeFake to improve discoverability.
* Link the merge method.
> Improve MemoryDb Javadoc

- ROADMAP.md
Add event listeners and JUnit extension to the roadmap.
---
> Add event listeners and JUnit extension to the roadmap.

- exonum-java-proofs/src/main/java/com/exonum/binding/storage/proofs/list/ListProofValidator.java
- exonum-java-proofs/src/test/java/com/exonum/binding/storage/proofs/list/ListProofValidatorTest.java
Replace Map with NavigableMap in ListProofValidator.
---
See: https://jira.bf.local/browse/ECR-2115
> ECR-2115 Replace Map with NavigableMap in ListProofValidator

- .gitignore
> Ignore VS Code configuration

- exonum-java-binding-core/rust/integration_tests/src/executor.rs
- exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
- exonum-java-binding-core/rust/integration_tests/src/test_service.rs
- exonum-java-binding-core/rust/integration_tests/tests/local_frame_capacity.rs
- exonum-java-binding-core/rust/integration_tests/tests/local_frame_memory_leak_executor.rs
- exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs
- exonum-java-binding-core/rust/src/proxy/service.rs
- exonum-java-binding-core/rust/src/proxy/transaction.rs
- exonum-java-binding-core/rust/src/runtime/java_service_runtime.rs
- exonum-java-binding-core/rust/src/storage/map_index.rs
- exonum-java-binding-core/rust/src/storage/proof_map_index.rs
- exonum-java-binding-core/rust/src/storage/value_set_index.rs
> Fix rustfmt

- .github/PULL_REQUEST_TEMPLATE.md
… so that one doesn't have to remove them.
Also, specify our project key in JIRA.
---
> Comment the instructions in PR template

- exonum-java-binding-bom/pom.xml
- exonum-java-binding-common/pom.xml
- exonum-java-binding-core/pom.xml
- exonum-java-binding-cryptocurrency-demo/pom.xml
- exonum-java-binding-fakes/pom.xml
- exonum-java-binding-qa-service/pom.xml
Use project.version to refer to the current version where applicable
---
> Use project.version to refer to the current version where applicable

- exonum-java-binding-cryptocurrency-demo/frontend/src/components/WalletHistory.vue
- exonum-java-binding-cryptocurrency-demo/frontend/src/pages/Wallet.vue
- exonum-java-binding-cryptocurrency-demo/frontend/src/plugins/blockchain.js
---
See: https://jira.bf.local/browse/ECR-2403
> [ECR-2403] Wallet history table on  user page

- exonum-java-binding-cryptocurrency-demo/frontend/package-lock.json
- exonum-java-binding-cryptocurrency-demo/frontend/package.json
- exonum-java-binding-cryptocurrency-demo/frontend/src/components/WalletHistory.vue
> [ECR-2422] bootstrap update and lint fix

- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/list/ListProofStatus.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/MapProofStatus.java
> Minor proof status fixes

- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/list/CheckedListProof.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/CheckedFlatMapProof.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/CheckedMapProof.java
- exonum-java-binding-common/src/test/java/com/exonum/binding/common/proofs/map/UncheckedFlatMapProofTest.java
- exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ProofMapContainsMatcher.java
> Minor proof fixes

- exonum-java-binding-common/src/main/java/com/exonum/binding/common/hash/HashCode.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/hash/HashFunction.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/CheckedProof.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/ProofStatus.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/list/CheckedListProof.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/list/ListProofStatus.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/CheckedMapProof.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/map/MapProofStatus.java
- exonum-java-binding-common/src/main/java/com/exonum/binding/common/serialization/Sint64Serializer.java
- exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/MapTestEntry.java
* Move common proof interfaces to the parent package to improve their discoverability
* Fix use of a `@Beta` API
* Fix Javadoc — links to non-present methods
* Reduce visibility of a private utility method
> Various fixes and improvements

- CHANGELOG.md
- ROADMAP.md
Update changelog - add date of v0.3, missing PR numbers and use the same formatting in old entries.
---
> Update changelog v0.3 [ECR-2549]

- CHANGELOG.md
> Reorder entries according to the end-user significance.

- CHANGELOG.md
> Add v0.3 release highlights [ECR-2551]

- exonum-java-binding-core/src/main/java/com/exonum/binding/proxy/NativeHandle.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/proxy/ProxyDestructor.java
- exonum-java-binding-core/src/test/java/com/exonum/binding/proxy/NativeHandleTest.java
NativeHandle toString() implementation added. ProxyDestructor toString() updated.
---
See: https://jira.bf.local/browse/ECR-2528
> NativeHandle toString() implemented [ECR-2528]

- exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/ApiController.java
- exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/Height.java
- exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/QaService.java
- exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java
- exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/ApiControllerIntegrationTest.java
- exonum-java-binding-qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java
---
See: https://jira.bf.local/browse/ECR-2541
> Added Blockchain endpoints to QA Service [ECR-2541]

- exonum-java-binding-core/rust/src/proxy/node.rs
- exonum-java-binding-core/src/main/java/com/exonum/binding/service/Node.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/service/NodeProxy.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/service/Service.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/service/adapters/UserServiceAdapter.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/service/adapters/UserTransactionAdapter.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/transaction/InternalTransactionContext.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/transaction/RawTransaction.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/transaction/Transaction.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/transaction/TransactionContext.java
- exonum-java-binding-core/src/main/java/com/exonum/binding/transaction/TransactionConverter.java
---
See: https://jira.bf.local/browse/ECR-2400
> [Experimental] Implement Java support of separated messages

- exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/MockInteraction.java
Replace custom JSON serialization with Gson
---
See: #572
> Replace custom JSON serialization with Gson

- exonum-java-binding-common/pom.xml
- exonum-java-binding-core/rust/Cargo.lock
- exonum-java-binding-core/rust/Cargo.toml
- exonum-java-binding-core/rust/integration_tests/Cargo.toml
- pom.xml
> Combine all dependency updates

- .travis.yml
- exonum-java-binding-core/rust/integration_tests/src/executor.rs
- exonum-java-binding-core/rust/integration_tests/src/mock/service.rs
- exonum-java-binding-core/rust/integration_tests/src/mock/transaction.rs
- exonum-java-binding-core/rust/integration_tests/src/test_service.rs
- exonum-java-binding-core/rust/integration_tests/tests/local_frame_capacity.rs
- exonum-java-binding-core/rust/integration_tests/tests/local_frame_memory_leak_executor.rs
- exonum-java-binding-core/rust/integration_tests/tests/local_frame_memory_leak_jvm.rs
- exonum-java-binding-core/rust/integration_tests/tests/transaction_proxy.rs
- exonum-java-binding-core/rust/integration_tests/tests/utils_errors.rs
- exonum-java-binding-core/rust/src/proxy/service.rs
- exonum-java-binding-core/rust/src/proxy/transaction.rs
- exonum-java-binding-core/rust/src/runtime/cmd.rs
- exonum-java-binding-core/rust/src/runtime/java_service_runtime.rs
- exonum-java-binding-core/rust/src/storage/map_index.rs
- exonum-java-binding-core/rust/src/storage/proof_map_index.rs
- exonum-java-binding-core/rust/src/storage/value_set_index.rs
Extended and configured build matrix
Fixed rust fmt errors
Fixed mac os openjdk8 installation issue
> Travis build fix

- exonum-java-binding-common/pom.xml
- exonum-java-binding-core/pom.xml
- pom.xml
Aggregates dependency updates from the bot.
---
> Update Java dependencies

- exonum-java-binding-core/rust/ejb-app/start_cryptocurrency_node.sh
Accept connections to public API on all network interfaces of a node,
so that clients with external addresses can use it
(e.g., a test driver, submitting them directly to the node public
endpoint).
---
> Accept connections on all interfaces:

- exonum-java-binding-cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/ApiController.java
- exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/ApiController.java
The controllers are created by the services, not Guice.
PR for master
> Remove redundant @Inject annotation

- README.md
Links were invalid because of update on exonum.com/doc
---
> Update links to documentation in README.md

- exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/IncrementCounterTx.java
> QA Service: Added detailed error message for Increment Counter Tx

- exonum-java-binding-core/src/main/java/com/exonum/binding/service/Node.java
> Fix after-merge style issues

- exonum-java-binding-common/src/main/java/com/exonum/binding/common/proofs/list/ListProofRootHashCalculator.java
- exonum-java-binding-common/src/test/java/com/exonum/binding/common/hash/HashCodeTest.java
- exonum-java-binding-common/src/test/java/com/exonum/binding/common/proofs/map/DbKeyTestUtils.java
- exonum-java-binding-common/src/test/java/com/exonum/binding/test/EqualsTester.java
- exonum-java-binding-common/src/test/java/com/exonum/binding/test/RelationshipTester.java
- exonum-java-binding-core/src/test/java/com/exonum/binding/blockchain/BlockchainTest.java
- exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ListSpliteratorTest.java
- exonum-java-binding-core/src/test/java/com/exonum/binding/storage/indices/ProofMapIndexProxyGroupIntegrationTest.java
- exonum-java-binding-fakes/src/main/java/com/exonum/binding/fakes/mocks/TestException.java
- exonum-java-binding-qa-service/src/main/java/com/exonum/binding/qaservice/transactions/QaTransactionJson.java
Apply various fixes suggested by the IDEA built-in static analyzer. See commit messages for details.
---
> Apply various fixes

- exonum-java-binding-parent/pom.xml
- pom.xml
> [New project structure] plugins fix

- exonum-java-binding-core/rust/ejb-app/Cargo.toml
- exonum-java-binding-core/rust/integration_tests/Cargo.toml
- exonum-java-binding-core/rust/integration_tests/tests/service_proxy.rs
- exonum-java-binding-core/rust/integration_tests/tests/service_runtime.rs
- exonum-java-binding-core/rust/integration_tests/tests/transaction_proxy.rs
- exonum-java-binding-core/rust/src/utils/resource_manager/mod.rs
`resource-manager` is defined as explicit dependency for `ejb-app` and integration tests.
---
See: https://jira.bf.local/browse/ECR-2855
> Fixed issue with tests on OSX [ECR-2855]

- .travis.yml
- .travis/run_travis_job.sh
> [New project structure] Fix travis path

- exonum-java-binding/CHANGELOG.md
- Add an overview of the release
- Expand on the description of some features.
---
> Update the changelog:

- exonum-java-binding/bom/pom.xml
- exonum-java-binding/common/pom.xml
- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/ejb-app/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/fakes/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/qa-service/pom.xml
- exonum-java-binding/service-archetype/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-binding/testing/pom.xml
- exonum-light-client/pom.xml
- pom.xml
> Bump project version for the next iteration

- exonum-java-binding/core/rust/integration_tests/src/mock/transaction.rs
- exonum-java-binding/core/rust/integration_tests/tests/node_context.rs
- exonum-java-binding/core/rust/integration_tests/tests/transaction_proxy.rs
- exonum-java-binding/core/rust/src/proxy/node.rs
- exonum-java-binding/core/rust/src/proxy/service.rs
- exonum-java-binding/core/rust/src/proxy/transaction.rs
Refactored and fixed some tests, removed unnecessary RawTransaction from TransactionProxy.
`passing_transaction_context` is a bit complex now, but I can't see the way of major simplification because of borrow checker requirements.
---
See: https://jira.bf.local/browse/ECR-2791
> Fix remaining issues in native part of separate messages [ECR-2791]

- exonum-light-client/README.md
- exonum-light-client/src/main/java/com/exonum/client/package-info.java
---
See: https://jira.bf.local/browse/ECR-2840
> [ECR-2840] Light Client: getting started and examples

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/ejb-app/Cargo.toml
- exonum-java-binding/core/rust/ejb-app/src/main.rs
- exonum-java-binding/core/rust/ejb-app/src/node_builder.rs
- exonum-java-binding/core/rust/src/lib.rs
- exonum-java-binding/core/rust/src/proxy/service.rs
- exonum-java-binding/core/rust/src/utils/mod.rs
- exonum-java-binding/core/rust/src/utils/services.rs
- exonum-java-binding/core/rust/src/utils/time_service.rs
- exonum-java-binding/pom.xml
- exonum-java-binding/time-service/pom.xml
- exonum-java-binding/time-service/src/main/java/com/exonum/binding/time/TimeSchema.java
- exonum-java-binding/time-service/src/main/java/com/exonum/binding/time/TimeSchemaProxy.java
- exonum-java-binding/time-service/src/main/java/com/exonum/binding/time/UtcZonedDateTimeSerializer.java
- exonum-java-binding/time-service/src/test/java/com/exonum/binding/time/TimeSchemaProxyIntegrationTest.java
- exonum-java-binding/time-service/src/test/java/com/exonum/binding/time/UtcZonedDateTimeSerializerTest.java
WIP: Add time service.
---
See: 
- https://jira.bf.local/browse/ECR-2811
- Closes #447
> Add time module [ECR-2811]

- exonum-light-client/pom.xml
- exonum-light-client/src/main/java/com/exonum/client/ExonumHttpClient.java
- exonum-light-client/src/main/java/com/exonum/client/SubmitTxRequest.java
- exonum-light-client/src/main/java/com/exonum/client/SubmitTxResponse.java
- exonum-light-client/src/test/java/com/exonum/client/ExonumHttpClientIntegrationTest.java
---
In my way `lombok` fits well in the LC module.
> LC: Added lombok

- exonum-light-client/pom.xml
Add distributionManagement needed for releasing this module to maven central.
---
> Update JLC pom

- .travis.yml
Build release branches on Travis
---
> Build release branches on Travis

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/src/proxy/service.rs
- exonum-java-binding/core/rust/src/proxy/transaction.rs
- exonum-java-binding/core/rust/src/storage/map_index.rs
- exonum-java-binding/core/rust/src/storage/proof_map_index.rs
- exonum-java-binding/core/rust/src/storage/value_set_index.rs
- exonum-java-binding/core/rust/src/utils/jni.rs
Experimental PR to discover possible conflicts before the release of JNI.rs version 0.11.0
---
> Update JNI to the latest release (0.11.0)

- exonum-java-binding/bom/pom.xml
- exonum-java-binding/time-service/src/main/java/com/exonum/binding/time/TimeSchema.java
- exonum-java-binding/time-service/src/main/java/com/exonum/binding/time/TimeSchemaProxy.java
- exonum-java-binding/time-service/src/test/java/com/exonum/binding/time/TimeSchemaIntegrationTest.java
- exonum-java-binding/time-service/src/test/java/com/exonum/binding/time/TimeSchemaProxyIntegrationTest.java
Add time-service to BOM and move factory method to TimeSchema interface.
---
> Update time service

- exonum-java-binding/time-oracle/src/main/java/com/exonum/binding/time/TimeSchemaProxy.java
- Adds missing space
- Refactor for clarity
---
> Fix error message:

- exonum-java-binding/time-oracle/src/main/java/com/exonum/binding/time/TimeSchemaProxy.java
> Add the link to the documentation on built-in services.

- exonum-java-binding/cryptocurrency-demo/frontend/package-lock.json
> Aggregate JS security updates

- exonum-java-binding/common/pom.xml
- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/fakes/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/qa-service/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
---
Added dependency management to parent pom for gson.
> Use dependency management for gson

- exonum-java-binding/CHANGELOG.md
Update changelog for ZDT JSON serializer
> Update changelog for ZDT JSON serializer

- exonum-java-binding/time-oracle/README.md
- exonum-light-client/src/main/java/com/exonum/client/ExonumHttpClient.java
- exonum-light-client/src/main/java/com/exonum/client/ExplorerApiHelper.java
---
* update time oracle readme
* update error messages replacements
> Minor fixes

- exonum-java-binding/pom.xml
- exonum-light-client/pom.xml
As the root project is an aggregator project, not a _parent_ project,
plugins are not inherited by the nested modules.
---
> Fix tidy plugin configuration

- exonum-java-binding/bom/pom.xml
- exonum-java-binding/common/pom.xml
- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/ejb-app/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/fakes/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/qa-service/pom.xml
- exonum-java-binding/service-archetype/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-binding/testing/pom.xml
- exonum-java-binding/time-oracle/README.md
- exonum-java-binding/time-oracle/pom.xml
- exonum-light-client/pom.xml
> Set version for the next iteration

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/time-oracle/README.md
- exonum-java-binding/time-oracle/pom.xml
- exonum-java-binding/time-oracle/src/main/java/com/exonum/binding/time/TimeSchema.java
- exonum-java-binding/time-oracle/src/test/java/com/exonum/binding/time/UtcZonedDateTimeSerializerTest.java
- exonum-light-client/CHANGELOG.md
- exonum-light-client/pom.xml
> Test the release merge builds

- exonum-java-binding/pom.xml
- exonum-light-client/pom.xml
Use descriptive id for the checkstyle execution.
---
> Use descriptive id for the checkstyle execution

- .travis.yml
- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/bom/pom.xml
- exonum-java-binding/common/pom.xml
- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/ejb-app/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/tests/service_proxy.rs
- exonum-java-binding/core/rust/integration_tests/tests/service_runtime.rs
- exonum-java-binding/core/rust/integration_tests/tests/transaction_proxy.rs
- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/fake-service/pom.xml
- exonum-java-binding/fakes/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/qa-service/pom.xml
- exonum-java-binding/service-archetype/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-binding/testing/pom.xml
- exonum-java-binding/time-oracle/README.md
- exonum-java-binding/time-oracle/pom.xml
- exonum-java-binding/time-oracle/src/main/java/com/exonum/binding/time/TimeSchema.java
- exonum-java-binding/time-oracle/src/test/java/com/exonum/binding/time/UtcZonedDateTimeSerializerTest.java
- exonum-light-client/CHANGELOG.md
- exonum-light-client/pom.xml
> Sync multiple services with master

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/core/src/main/java/com/exonum/binding/storage/indices/EntryIndexProxy.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/storage/indices/EntryIndexProxyIntegrationTest.java
- exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java
- exonum-java-binding/time-oracle/README.md
---
See: https://jira.bf.local/browse/ECR-3015
> [ECR-3015] Add toOptional to Entry Index

- exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/LoadedServiceDefinition.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/Pf4jServiceLoader.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/ReflectiveModuleSupplier.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/ServiceLoader.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/runtime/ServiceRuntimeBootstrap.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/service/AbstractServiceModule.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/storage/database/Snapshot.java
- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/CryptocurrencyServiceImpl.java
---
See: https://jira.bf.local/browse/ECR-3008
> Resolve some TODOs [ECR-3008, ECR-2796]

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/ejb-app/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/core/rust/src/runtime/cmd.rs
Updated to Exonum v0.11
---
See: https://jira.bf.local/browse/ECR-3038
> Update to Exonum 0.11 [ECR-3038]

- exonum-java-binding/common/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-light-client/pom.xml
> Aggregate dependencies updates

- exonum-java-binding/core/rust/exonum-java/start_cryptocurrency_node.sh
- exonum-java-binding/core/rust/exonum-java/start_qa_node.sh
---
See: https://jira.bf.local/browse/ECR-3094
> Fix exonum-java scripts and clarify their usage [ECR-3094]

- exonum-java-binding/packaging/pom.xml
> Disable deploy for packaging module

- exonum-java-binding/core/rust/src/testkit/mod.rs
> Fix nativeCreateTestkit method

- exonum-java-binding/core/rust/src/testkit/mod.rs
> Use -1 for validator Id in case of auditor node

- .travis.yml
It is reported they work now.
This reverts commit cf7e9b94
---
See: https://jira.bf.local/browse/ECR-3127
> Re-enable builds on OpenJDK 12 [ECR-3127]:

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/core/src/main/java/com/exonum/binding/blockchain/Blockchain.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/blockchain/CoreSchemaProxy.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/blockchain/BlockchainTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/blockchain/CoreSchemaProxyIntegrationTest.java
Add pool transaction hashes access.
---
See: https://jira.bf.local/browse/ECR-3136
> Add pool transaction hashes access [ECR-3136]

- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/rust/src/handle/resource_manager/stub.rs
> Fix build after #844

- exonum-java-binding/core/rust/src/testkit/mod.rs
> Poll events on Snapshot creation in TestKit

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/core/checkstyle-suppressions.xml
- exonum-java-binding/core/src/main/java/com/exonum/binding/blockchain/Block.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/blockchain/BlockTest.java
- exonum-light-client/checkstyle-suppressions.xml
- exonum-light-client/pom.xml
- exonum-light-client/src/main/java/com/exonum/client/response/Block.java
- exonum-light-client/src/test/java/com/exonum/client/response/BlockTest.java
Exonum-Benchmarking, a major client of the light client, proved it to be needed.
---
> Add Block#isEmpty

- .travis/run_travis_job.sh
> Ignore results of cargo audit

- exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplIntegrationTest.java
- exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/TestKit.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java
Such method allows to simplify the assertions.
---
> Add getTransactionPool

- exonum-light-client/CHANGELOG.md
- exonum-light-client/README.md
- exonum-light-client/pom.xml
---
See: https://jira.bf.local/browse/ECR-2920
> [ECR-2920] Docs update for JLC v0.2.0

- exonum-java-binding/app/pom.xml
- exonum-java-binding/app/src/main/java/com/exonum/binding/app/ServiceRuntimeBootstrap.java
- exonum-java-binding/pom.xml
Produce and log the build metadata at application startup:
- version
- short Git revision
- build time in UTC.
---
See: https://jira.bf.local/browse/ECR-3150
> Log the build metadata at startup: [ECR-3150]

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/cryptocurrency-demo/frontend/package-lock.json
- exonum-java-binding/cryptocurrency-demo/frontend/package.json
- exonum-java-binding/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-light-client/pom.xml
Please see the indy commits.
---
> Aggregate dependency updates

- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/ByteStrings.java
- exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/CryptocurrencySchema.java
- exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/CryptocurrencyService.java
- exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/CryptocurrencyServiceImpl.java
- exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTx.java
- exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/transactions/TransferTx.java
- exonum-java-binding/cryptocurrency-demo/src/main/proto/transactions.proto
- exonum-java-binding/cryptocurrency-demo/src/main/proto/wallet.proto
- exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTxTest.java
- exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransactionUtils.java
- exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxHistoryTest.java
- exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxTest.java
- exonum-java-binding/cryptocurrency-demo/start-cryptocurrency-demo.sh
Make schema and transfer tx the same as in Rust.
- **https://jira.bf.local/browse/ECR-3208**
- **https://github.com/exonum/exonum/tree/v0.11.0/examples/cryptocurrency-advanced/backend/src**
> Clone cryptocurrency-advanced [ECR-3208]

- CONTRIBUTING.md
- exonum-java-binding/core/pom.xml
Run `mvn clean -DcleanRust` and you are clean :shower: 
---
See: https://jira.bf.local/browse/ECR-3287
> Add clean Rust target Maven command [ECR-3287].

- exonum-java-binding/core/checkstyle-suppressions.xml
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxyIntegrationTest.java
Illustrate the structure of an MPT that is formed when the entries,
produced by this method, are added to the ProofMap.
---
> Illustrate the resulting Merkle-Patricia tree:

- exonum-light-client/src/test/java/com/exonum/client/ExonumHttpClientBlocksIntegrationTest.java
- exonum-light-client/src/test/java/com/exonum/client/ExonumHttpClientIntegrationTest.java
- exonum-light-client/src/test/java/com/exonum/client/ExonumHttpClientWithPrefixIntegrationTest.java
- exonum-light-client/src/test/java/com/exonum/client/RecordedRequestMatchers.java
- exonum-light-client/src/test/java/com/exonum/client/TestUtils.java
> Improve the path matching readability

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/doc/Migration_guide_0.7.md
> Update the changelog and the migration guide

- exonum-java-binding/app/pom.xml
- exonum-java-binding/bom/pom.xml
- exonum-java-binding/common/pom.xml
- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/util/LibraryLoader.java
- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/fake-service/pom.xml
- exonum-java-binding/fakes/pom.xml
- exonum-java-binding/integration-tests/pom.xml
- exonum-java-binding/packaging/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/qa-service/pom.xml
- exonum-java-binding/service-archetype/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-binding/testing/pom.xml
- exonum-java-binding/testkit/pom.xml
- exonum-java-binding/time-oracle/README.md
- exonum-java-binding/time-oracle/pom.xml
> Update project version for the next iteration

- exonum-light-client/README.md
- exonum-light-client/pom.xml
Merge after 0.7.0 release.
Update EJB version to 0.7.0 in light client.
> Update EJB version to 0.7.0 in light client

- ROADMAP.md
- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/core/pom.xml
- exonum-java-binding/doc/Migration_guide_0.7.md
- exonum-java-binding/generate-javadocs.sh
- exonum-java-binding/integration-tests/pom.xml
- exonum-java-binding/package_app.sh
> Merge the updates from 0.7.0 release branch 

- exonum-java-binding/common/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-binding/testkit/pom.xml
- exonum-light-client/pom.xml
> Aggregate dep updates

- .travis.yml
Do not cache light client artifacts on Travis and re-upload them
on each build — they are built by this project.
---
> Update the travis cache configuration:

- exonum-java-binding/testkit/README.md
Merge after 0.7.0 release.
Add README.md to TestKit module.
Q: Should we put more details or a link to documentation is sufficient in this case?
> Add README.md to TestKit module

- exonum-java-binding/core/rust/integration_tests/tests/service_runtime.rs
- exonum-java-binding/core/rust/src/storage/proof_map_index.rs
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxyIntegrationTest.java
- exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/CryptocurrencySchemaIntegrationTest.java
- exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/CreateWalletTxTest.java
- exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxHistoryTest.java
- exonum-java-binding/cryptocurrency-demo/src/test/java/com/exonum/binding/cryptocurrency/transactions/TransferTxTest.java
- exonum-java-binding/fakes/src/test/java/com/exonum/binding/fakes/services/service/TestServiceIntegrationTest.java
JNI code adapted to new MerkleDb API. Uncommented a set of integration tests.
---
See: https://jira.bf.local/browse/ECR-3321
> Updating JNI code for ProofMapIndex. [ECR-3321]

- exonum-java-binding/core/rust/src/utils/jni_cache.rs
> Fix a typo

- CONTRIBUTING.md
> Fix rustfmt instructions

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseIndexProxyTestable.java
Fixed integration tests that check the type of index.
---
See: https://jira.bf.local/browse/ECR-3415
> Fixed index type integration tests [ECR-3415]

- .travis.yml
- CONTRIBUTING.md
- exonum-java-binding/core/pom.xml
- exonum-java-binding/tests_profile
---
See: https://jira.bf.local/browse/ECR-3459
> Fall back to Rust 1.36.0 [ECR-3459]

- .travis.yml
- CONTRIBUTING.md
- exonum-java-binding/core/pom.xml
- exonum-java-binding/tests_profile
---
See: https://jira.bf.local/browse/ECR-3459
> Revert to 1.36 [ECR-3459] [MerkleDB]

- exonum-java-binding/common/src/test/java/com/exonum/binding/common/message/BinaryTransactionMessageTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/map/DbKeyCommonPrefixParameterizedTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/map/DbKeyComparisonParameterizedTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/map/KeyBitSetIsPrefixParameterizedTest.java
- exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/transactions/QaTransactionConverterTest.java
- exonum-light-client/src/test/java/com/exonum/client/SystemApiHelperTest.java
for higher clarity and consistency.
---
> Use arguments instead of Arguments.of

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
closes #1091 #1092 #1093 #1094 #1095 #1096
---
> Update Rust dependencies

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/CheckedListProof.java
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/CheckedListProofImpl.java
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/ListProofHashCalculator.java
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/ListProofOfAbsence.java
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/ListProofStatus.java
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/list/ListProofStructureValidator.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/list/ListProofStructureValidatorTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/proofs/list/ListProofUtils.java
- exonum-java-binding/core/rust/src/storage/proof_list_index.rs
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofListIndexProxy.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/StoragePreconditions.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofListContainsMatcher.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ProofListIndexProxyIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/StoragePreconditionsTest.java
Add proofs of absence for ListProof.
---
See: https://jira.bf.local/browse/ECR-3413
> Add proofs of absence for ListProof [ECR-3413]

- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/rust/exonum-java/start_cryptocurrency_node.sh
- exonum-java-binding/core/rust/exonum-java/start_qa_node.sh
- exonum-java-binding/package_app.sh
Fixing problems with dynamic linking by switching to using the `java_bindings`  library from dependencies of the `exonum-java`
---
See: https://jira.bf.local/browse/ECR-3468
> Fix dynamic linking [ECR-3468]

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/app/pom.xml
- exonum-java-binding/benchmarks/pom.xml
- exonum-java-binding/bom/pom.xml
- exonum-java-binding/common/pom.xml
- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/util/LibraryLoader.java
- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/fake-service/pom.xml
- exonum-java-binding/fakes/pom.xml
- exonum-java-binding/integration-tests/pom.xml
- exonum-java-binding/packaging/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/qa-service/pom.xml
- exonum-java-binding/service-archetype/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-binding/testing/pom.xml
- exonum-java-binding/testkit/pom.xml
- exonum-java-binding/time-oracle/README.md
- exonum-java-binding/time-oracle/pom.xml
- Updated version from `0.8.0-SNAPSHOT` to `0.8.0`
- Updated the `Unreleased` section at the end of Changelog.
---
> Update EJB to 0.8.0

- exonum-java-binding/core/rust/exonum-java/TUTORIAL.md
> Update App Tutorial for the 0.8.0 release

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
> Aggregate Rust dependencies updates from Dependabot

- exonum-java-binding/time-oracle/pom.xml
- exonum-java-binding/time-oracle/src/test/java/com/exonum/binding/time/UtcZonedDateTimeSerializerTest.java
Enable checkstyle and fix style violations.
---
> Enable checkstyle for time-oracle:

- README.md
- ROADMAP.md
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/cryptocurrency-demo/frontend/package.json
Update the contact Exonum email to contact@exonum.com
---
> Update the contact Exonum email

- exonum-light-client/README.md
> Add a badge with the most recent LC version.

- exonum-java-binding/core/rust/src/storage/core_schema.rs
- exonum-java-binding/core/rust/src/storage/mod.rs
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/CoreSchemaProxyIntegrationTest.java
---
See: https://jira.bf.local/browse/ECR-3722
> Reenable Core Schema [ECR-3722]

- exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/CoreSchemaProxy.java
Fix consensus config index name.
> Fix consensus config index name

- exonum-java-binding/pom.xml
> Fix coveralls

- exonum-java-binding/core/rust/src/proxy/runtime.rs
> Swap variables in executeTx method

- exonum-java-binding/launcher-plugin/exonum_java_runtime_plugin/plugin.py
> Update launcher plugin with recent changes to proto files

- exonum-java-binding/benchmarks/pom.xml
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
- exonum-java-binding/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-light-client/pom.xml
> Update deps [dependabot]

- exonum-java-binding/core/checkstyle-suppressions.xml
- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/src/node.rs
- exonum-java-binding/core/rust/integration_tests/tests/node_context.rs
- exonum-java-binding/core/rust/src/proxy/node.rs
- exonum-java-binding/core/rust/src/proxy/runtime.rs
- exonum-java-binding/core/rust/src/testkit/mod.rs
- exonum-java-binding/core/rust/src/utils/errors.rs
- exonum-java-binding/core/rust/src/utils/jni_cache.rs
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/GuiceServicesFactory.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/RuntimeTransport.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceFrameworkModule.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceWrapper.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServicesFactory.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/transport/Server.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/transport/VertxServer.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/GuiceServicesFactoryTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/RuntimeTransportTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeConfigurationIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceWrapperTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/transport/VertxServerIntegrationTest.java
- exonum-java-binding/pom.xml
- exonum-java-binding/run_maven_tests.sh
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java
- run_all_tests.sh
> Ds update exonum 4

- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/TransactionConverter.java
- exonum-java-binding/cryptocurrency-demo/pom.xml
- exonum-java-binding/run_maven_tests.sh
- exonum-java-binding/service-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MySchema.java
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MyService.java
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MyTransactionConverter.java
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/test/java/MyServiceIntegrationTest.java
- exonum-java-binding/service-archetype/src/test/resources/projects/archetype.properties
- run_all_tests.sh
Support DS in service-archetype module.
---
See: https://jira.bf.local/browse/ECR-3595
> Support DS in service-archetype module [ECR-3595]

- exonum-java-binding/common/pom.xml
Make protobuf dependency in common transitional. See https://github.com/exonum/exonum-java-binding/pull/1244#discussion_r351258568
> Make protobuf dependency in common transitive

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/src/utils/jni_cache.rs
Does not include bumping `futures` dependency.
---
> Update Rust deps [dependabot]

- exonum-java-binding/CHANGELOG.md
Update changelog for the `0.9.0-rc1` release.
> Update changelog for the 0.9.0-rc1 release

- CONTRIBUTING.md
> Adjust contrib guide

- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
Use only minor versions for better readability and less changes for version update
---
> Use minor versions in Cargo.toml

- exonum-java-binding/generate-javadocs.sh
- Build and install only the required modules
- Set the environment variables
---
> Improve Javadoc generation script:

- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Configuration.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Service.java
> Clarify that reconfiguration is supported

- CONTRIBUTING.md
- exonum-java-binding/run_maven_tests.sh
- run_all_tests.sh
Specify the project list for root and exonum-java-binding directories.
Update scripts to match.
---
> Clarify build instructions:

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/src/node.rs
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/core/rust/integration_tests/tests/runtime_bootstrap.rs
- exonum-java-binding/core/rust/src/proxy/runtime.rs
- exonum-java-binding/core/rust/src/testkit/mod.rs
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/DispatcherSchema.java
- exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplTest.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitExtensionTest.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTestUtils.java
- exonum-java-binding/time-oracle/src/main/java/com/exonum/binding/time/TimeSchemaProxy.java
Updated to the published release 0.13.0-rc.2 of Exonum core.
---
See: https://jira.bf.local/browse/ECR-3937
> Update to Exonum 0.13 [ECR-3937]

- exonum-light-client/README.md
Fix the list rendering and reword the sentence.
[skip ci]
---
> Reword the LC readme

- exonum-java-binding/core/rust/exonum-java/src/node.rs
The App was broken (probably when updating to the latest Exonum revision). 
---
See: https://jira.bf.local/browse/ECR-3841
> Add Supervisor service to the list of service factories [ECR-3841]

- exonum-java-binding/core/rust/exonum-java/qa-service.yml
> Fix qa-service.yml launcher config

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/app/pom.xml
Deploy the exonum-java-app module, upon which
the testkit depends.
---
See: https://jira.bf.local/browse/ECR-3987
> Deploy the exonum-java-app module [ECR-3987]

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/pom.xml
- exonum-light-client/pom.xml
> Aggregate dependencies

- exonum-light-client/README.md
- exonum-light-client/src/main/java/com/exonum/client/ExonumClient.java
- Split the long line in examples
- Add language type
- Clarify what kind of address must be set
> Improve LC docs:

- exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/Block.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/serialization/BlockSerializer.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/BlockTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/Blocks.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/serialization/BlockSerializerTest.java
---
See: https://jira.bf.local/browse/ECR-4021
> [ECR-4021] Reflect proto changes for Block

- exonum-java-binding/app/pom.xml
- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/rust/integration_tests/src/vm.rs
- exonum-java-binding/run_native_integration_tests.sh
---
See: https://jira.bf.local/browse/ECR-4094
> Use core classpath for native integration tests [ECR-4094]

- exonum-java-binding/core/rust/exonum-java/start_node.sh
- exonum-java-binding/cryptocurrency-demo/start-node.sh
New option was added in used Core revision
---
> Update start-node scripts to the recent master

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/src/main.rs
- exonum-java-binding/core/rust/exonum-java/src/node.rs
Explorer is now a separated service, not internal core functionality.
---
> Enable explorer service

- exonum-java-binding/app/src/main/java/com/exonum/binding/app/ServiceRuntimeBootstrap.java
> Use predefined system properties.

- exonum-java-binding/common/pom.xml
- exonum-java-binding/core/pom.xml
- exonum-java-binding/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/pom.xml
- exonum-java-binding/testkit/pom.xml
- exonum-light-client/pom.xml
- exonum-light-client/src/test/java/com/exonum/client/response/BlockTest.java
Also, perform some adjustments — see individual commits.
> Aggregate updates

- exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaExecutionError.java
- exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java
- exonum-java-binding/qa-service/src/main/proto/config.proto
- exonum-java-binding/qa-service/src/test/java/com/exonum/binding/qaservice/QaServiceImplTest.java
---
See: https://jira.bf.local/browse/ECR-4144
> [ECR-4144] Add resume to QA service

- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Access.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Fork.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Snapshot.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/KeySetIndexProxy.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ListIndexProxy.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/MapIndexProxy.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofEntryIndexProxy.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofListIndexProxy.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxy.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxy.java
Improve documentation after recent Access introduction:
- Warn that IndexT#newInstance are not for services.
- Specify address resolution rules in Accesses.
---
> Improve documentation after Access:

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/src/proxy/node.rs
- exonum-java-binding/core/rust/src/proxy/runtime.rs
- exonum-java-binding/core/rust/src/storage/access.rs
- exonum-java-binding/core/rust/src/storage/blockchain.rs
- exonum-java-binding/core/rust/src/storage/db.rs
- exonum-java-binding/core/rust/src/storage/entry.rs
- exonum-java-binding/core/rust/src/storage/fork.rs
- exonum-java-binding/core/rust/src/storage/key_set_index.rs
- exonum-java-binding/core/rust/src/storage/list_index.rs
- exonum-java-binding/core/rust/src/storage/map_index.rs
- exonum-java-binding/core/rust/src/storage/mod.rs
- exonum-java-binding/core/rust/src/storage/proof_entry.rs
- exonum-java-binding/core/rust/src/storage/proof_list_index.rs
- exonum-java-binding/core/rust/src/storage/proof_map_index.rs
- exonum-java-binding/core/rust/src/storage/proof_map_index_next.rs
- exonum-java-binding/core/rust/src/storage/raw_proof_map_index.rs
- exonum-java-binding/core/rust/src/storage/temporarydb.rs
- exonum-java-binding/core/rust/src/storage/value_set_index.rs
- exonum-java-binding/core/rust/src/testkit/mod.rs
- exonum-java-binding/core/rust/src/utils/conversion.rs
- exonum-java-binding/core/rust/src/utils/mod.rs
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/AbstractAccess.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseIndexProxyTestable.java
Uses GenericAccess (aka ErasedAccess) from Core instead of View. Depends on custom Exonum Core fork.
Typos are _highly_ possible.
---
See: https://jira.bf.local/browse/ECR-4177
> Generic storage access control [ECR-4157, ECR-4177]

- exonum-java-binding/core/rust/src/storage/access.rs
> Add AbstractAccess#canModify native method

- exonum-java-binding/core/rust/src/proxy/runtime.rs
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/BlockchainData.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/AbstractAccess.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/database/Prefixed.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/blockchain/BlockchainDataIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceNodeProxyIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceWrapperIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/PrefixedIntegrationTest.java
See commits for details.
---
See: https://jira.bf.local/browse/ECR-4176
> Post native fixes for bd ECR-4176

- .travis.yml
- exonum-java-binding/core/rust/src/proxy/runtime.rs
- exonum-java-binding/core/rust/src/storage/access.rs
- exonum-java-binding/core/rust/src/storage/blockchain_data.rs
- exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/BlockchainIntegrationTest.java
- exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/TimeSchemaProxyIntegrationTest.java
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MySchema.java
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/main/java/MyService.java
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/src/test/java/MyServiceIntegrationTest.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestService.java
> Various post-native fixes/updates (BlockchainData) [ECR-4176]

- exonum-java-binding/core/rust/integration_tests/tests/node_context.rs
- exonum-java-binding/core/rust/src/lib.rs
- exonum-java-binding/core/rust/src/proxy/node.rs
- exonum-java-binding/core/rust/src/storage/access.rs
- exonum-java-binding/core/rust/src/storage/blockchain.rs
- exonum-java-binding/core/rust/src/storage/blockchain_data.rs
- exonum-java-binding/core/rust/src/storage/entry.rs
- exonum-java-binding/core/rust/src/storage/fork.rs
- exonum-java-binding/core/rust/src/storage/key_set_index.rs
- exonum-java-binding/core/rust/src/storage/list_index.rs
- exonum-java-binding/core/rust/src/storage/map_index.rs
- exonum-java-binding/core/rust/src/storage/prefixed.rs
- exonum-java-binding/core/rust/src/storage/proof_entry.rs
- exonum-java-binding/core/rust/src/storage/proof_list_index.rs
- exonum-java-binding/core/rust/src/storage/proof_map_index.rs
- exonum-java-binding/core/rust/src/storage/proof_map_index_next.rs
- exonum-java-binding/core/rust/src/storage/raw_proof_map_index.rs
- exonum-java-binding/core/rust/src/storage/readonly_erased_access.rs
- exonum-java-binding/core/rust/src/storage/temporarydb.rs
- exonum-java-binding/core/rust/src/storage/value_set_index.rs
- exonum-java-binding/core/rust/src/testkit/time_provider.rs
- exonum-java-binding/core/rust/src/utils/conversion.rs
Based on #1409 
---
See: https://jira.bf.local/browse/ECR-4206
> Optimize imports from exonum_merkledb [ECR-4206]

- exonum-java-binding/core/rust/src/proxy/runtime.rs
> Return error in Runtime::migrate method

- exonum-light-client/src/main/java/com/exonum/client/ExplorerApiHelper.java
- exonum-light-client/src/test/java/com/exonum/client/ExonumHttpClientIntegrationTest.java
- exonum-light-client/src/test/java/com/exonum/client/ExplorerApiHelperTest.java
s/content/message.
---
See: https://jira.bf.local/browse/ECR-4218
> Update the field name of transaction response [ECR-4218]:

- exonum-java-binding/cryptocurrency-demo/src/main/java/com/exonum/binding/cryptocurrency/TransactionError.java
- exonum-java-binding/doc/Migration_guide_0.10.md
Links are to be updated separately.
My perception is that's mostly enough — we also have quite a solid changelog on top of that. Also, the diff.
---
See: https://jira.bf.local/browse/ECR-4240
> Add a migration guide for 0.10 [ECR-4240]:

- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceWrapper.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/Service.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceWrapperIntegrationTest.java
- exonum-java-binding/qa-service/src/main/java/com/exonum/binding/qaservice/QaServiceImpl.java
It must be plural as many transactions may be processed in a block
and for symmetry with `afterTransactions`.
---
> Fix the `beforeTransactions` method name:

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/src/lib.rs
- exonum-java-binding/core/rust/src/storage/value_set_index.rs
> Remove dependency on exonum_crypto

- exonum-java-binding/core/spotbugs-exclude.xml
> Remove redundant suppressions [ECR-4199].

- .travis.yml
> Add Travis jobs for nightly Rust and OpenJDK EA [ECR-3462]

- .travis.yml
- .travis/run_travis_job.sh
Use minimal profile for CI builds: https://github.com/rust-lang/rustup#profiles
Keep the explicit installation of clippy & rustfmt in the SA job.
---
> Check tools installed

- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/NativeResourceManagerIntegrationTest.java
Test the new feature added to rm in #1189 in Java ITs (👋 @DarkEld3r ).
> Add resource manager test to Java ITs

- exonum-java-binding/service-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/deploy-start-config.yml
Commits to review: the last one
---
See: https://jira.bf.local/browse/ECR-4290
> Add a template of exonum-launcher configuration file [ECR-4290]

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/app/src/main/java/com/exonum/binding/app/ServiceRuntimeBootstrap.java
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/crypto/Ed25519CryptoFunction.java
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/crypto/KeyPair.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/message/TransactionMessageBuilderTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/TransactionMessageSerializerTest.java
- exonum-java-binding/core/rust/src/testkit/mod.rs
- exonum-java-binding/exonum_launcher_java_plugins/requirements.txt
- exonum-java-binding/service-archetype/src/main/resources-filtered/archetype-resources/__rootArtifactId__-service/pom.xml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/deploy-start-config.yml
- exonum-java-binding/service-archetype/src/main/resources/archetype-resources/start-testnet.sh
Various fixes to artifact, plugin and the service runtime bootstrap loader, discovered during tutorial development. 
*Review commit-by-commit.*
> Various post-tutorial fixes

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/common/src/main/java/com/exonum/binding/common/serialization/StandardSerializers.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/Blockchain.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/blockchain/CoreSchema.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/AbstractEntryIndexProxy.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/EntryIndex.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseEntryIndexProxyIntegrationTest.java
- exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/BlockchainIntegrationTest.java
- Add Blockchain#getNumTransactions [ECR-4062]. 
- Also add Optional-like EntryIndex#orElse.
- Link little-endian byte order.
- Add Blockchain#getNextHeight [ECR-4096].
> Extend Blockchain [ECR-4096, ECR-4062].

- exonum-java-binding/core/rust/Cargo.lock
- exonum-java-binding/core/rust/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/Cargo.toml
- exonum-java-binding/core/rust/exonum-java/qa-service.yml
- exonum-java-binding/core/rust/integration_tests/Cargo.toml
- exonum-java-binding/core/rust/src/proxy/runtime.rs
- exonum-java-binding/core/rust/src/testkit/mod.rs
- exonum-java-binding/doc/Migration_guide_0.10.md
- exonum-java-binding/exonum_launcher_java_plugins/sample-config.yml
> Use Exonum 1.0.0

- exonum-java-binding/common/src/main/java/com/exonum/binding/common/proofs/InvalidProofException.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/proxy/Cleaner.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/proxy/CloseFailuresException.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceLoadingException.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/TransactionExtractor.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/UnexpectedExecutionException.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/ExecutionException.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/TransactionSubmissionException.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/storage/indices/ProofMapIndexProxy.java
- exonum-java-binding/integration-tests/pom.xml
- exonum-java-binding/integration-tests/src/test/resources/log4j2-test.xml
- exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/TestKitExtension.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitExtensionTest.java
Also, enable PF4J logs in ITs just in case. 
See individual commits for details.
> Resolve some compiler warnings

- .travis.yml
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/BoolSerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/DoubleSerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/Fixed32SerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/Fixed64SerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/FloatSerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/HashCodeSerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/NoOpSerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/PrivateKeySerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/ProtobufReflectiveSerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/PublicKeySerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/Sint32SerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/Sint64SerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/StandardSerializersTestUtils.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/StringSerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/TransactionMessageSerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/Uint32SerializerTest.java
- exonum-java-binding/common/src/test/java/com/exonum/binding/common/serialization/Uint64SerializerTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/proxy/CleanerTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/database/TemporaryDbIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/AbstractIndexProxyTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/BaseProofMapIndexProxyIntegrationTestable.java
- exonum-java-binding/testkit/src/main/java/com/exonum/binding/testkit/TestKitExtension.java
- pom.xml
> Fix sonar issues in tests

- exonum-java-binding/common/src/main/java/com/exonum/binding/common/hash/MessageDigestHashFunction.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/util/LibraryLoader.java
- exonum-java-binding/cryptocurrency-demo/frontend/server.js
- exonum-java-binding/testing/src/main/java/com/exonum/binding/test/Bytes.java
---
See: https://jira.bf.local/browse/ECR-4394
> [ECR-4394] Fix security issues

- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/KeySetIndexProxyIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/MapIndexProxyIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/storage/indices/ValueSetIndexProxyIntegrationTest.java
- exonum-java-binding/integration-tests/src/test/java/com/exonum/binding/test/BlockchainDataIntegrationTest.java
- exonum-java-binding/site-examples/src/test/java/com/exonum/binding/example/testing/TestkitExamples2Test.java
- exonum-java-binding/site-examples/src/test/java/com/exonum/binding/example/testing/TestkitExamplesTest.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitExtensionTest.java
- exonum-java-binding/testkit/src/test/java/com/exonum/binding/testkit/TestKitTest.java
---
See: https://jira.bf.local/browse/ECR-4395
> [ECR-4395] Fix code smells

- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/migration/MigrationScript.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/migration/package-info.java
---
See: https://jira.bf.local/browse/ECR-4408
> Add migration script

- exonum-java-binding/CHANGELOG.md
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/LoadedServiceDefinition.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/Pf4jServiceLoader.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ReflectiveExtensionSupplier.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/migration/MigrationScript.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/GuiceServicesFactoryTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/Pf4jServiceLoaderIntegrationTestable.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ReflectiveExtensionSupplierTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/TestMigrationScript1.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/TestServiceModuleInaccessibleCtor.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/module/PackagePrivateModule.java
---
See: https://jira.bf.local/browse/ECR-4409
> [ECR-4409] Add migration scripts loading

- exonum-java-binding/common/src/main/java/com/exonum/binding/common/runtime/ServiceArtifactId.java
- exonum-java-binding/core/pom.xml
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntime.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapter.java
- exonum-java-binding/core/src/main/java/com/exonum/binding/core/service/migration/MigrationScript.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeAdapterIntegrationTest.java
- exonum-java-binding/core/src/test/java/com/exonum/binding/core/runtime/ServiceRuntimeIntegrationTest.java
- exonum-java-binding/pom.xml
---
See: https://jira.bf.local/browse/ECR-4410
> [ECR-4410] Add migration scripts lookup in Java services runtime

- exonum-java-binding/core/rust/src/cmd/mod.rs
- exonum-java-binding/core/rust/src/cmd/run.rs
- exonum-java-binding/core/rust/src/cmd/run_dev.rs
> Fix rust imports

- exonum-java-binding/core/pom.xml
- exonum-java-binding/pom.xml
> Update exec plugin
